(#839) Time Picker Pass Though
NCIOCPL/ncids pull request #1027
Opened 2023-06-08 14:55 UTC by karlikpj

Closes #839

Add Time Picker pass through component.

2023-06-13 14:51 UTC, olitharp-nci commented on docs/content/index.mdx
> +- [NCI Hero](./components/nci-hero)
can you add to your commit message that you fixed the alphabetizing of the components

2023-06-13 14:52 UTC, olitharp-nci commented on docs/content/index.mdx
> +- [Time Picker](https://designsystem.digital.gov/components/ime-picker)
```suggestion
- [Time Picker](https://designsystem.digital.gov/components/time-picker)
```

2023-06-13 14:53 UTC, olitharp-nci commented on docs/content/index.mdx
> +
fix this extra line

2023-08-02 13:54 UTC, olitharp-nci requested changes

2023-08-02 13:54 UTC, olitharp-nci commented on docs/content/index.mdx
> +  <<<<<<< HEAD
can you fix this conflict

2023-08-02 14:49 UTC, olitharp-nci requested changes

2023-08-02 14:49 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_usa-in-page-navigation_link_active_0_document_0_tablet.png
😭 i thought we fixed this

cannot merge this with this regression

2023-08-02 15:52 UTC, olitharp-nci approved these changes

2023-08-03 15:12 UTC, sarinapadilla approved these changes

2023-08-04 14:17 UTC, merged