(#1024) (#1016) Updates USA-Section in Example Pages and Storybook
NCIOCPL/ncids pull request #1028
Opened 2023-06-08 17:20 UTC by dlescarbeau

- Closes #1024
- Closes #1016

2023-06-14 16:28 UTC, dev-rana-publicis requested changes

2023-06-14 16:28 UTC, dev-rana-publicis commented on testing/ncids-css-testing/stories/components/nci-cta-strip/default.stories.jsx
> +<section class="usa-section usa-section--dark">
CTA Strip standalone and in the hero have been changed to divs

2023-06-14 16:28 UTC, dev-rana-publicis commented on packages/ncids-css/packages/nci-hero/internal/_nci-hero.scss
> +	background-color: color($theme-color-accent-cool-darker);
Refer to the comment about moving the CTA strip in the hero variant. By moving the CTA strip inside of `<div class="nci-hero nci-hero--with-cta-strip">`, you won't need that background-color line. The parent div should dictate the color of the CTA strip

2023-06-14 17:28 UTC, andyvanavery commented
Reviewed and approved by Andy Van Avery on 14JUN2023. Needs Design review.

2023-06-15 14:59 UTC, dev-rana-publicis commented
The PR looks good to me after combing through it multiple times. Only aspect that I might add is the `aria-label` on the anchor tags to show that we are using `aria-label` and not `alt` text.

2023-06-15 15:05 UTC, dev-rana-publicis requested changes

2023-06-15 15:05 UTC, dev-rana-publicis commented on testing/ncids-css-testing/stories/templates/cgov-home/default.stories.jsx
>  							alt="NCI Equity and Inclusion Program"
Change `alt` to `aria-label`

2023-06-15 19:59 UTC, dev-rana-publicis approved these changes

2023-06-22 14:46 UTC, monika-jaeger approved these changes

2023-06-22 14:50 UTC, arcepaul approved these changes

2023-06-22 14:50 UTC, merged