(#1026) Update example page content
NCIOCPL/ncids pull request #1065
Opened 2023-06-22 10:21 UTC by karlikpj

Closes #1026

Updating content on example pages to match active site

2023-06-23 14:01 UTC, olitharp-nci requested changes
Sorry, looks like Imma be blocking this until we get the image situation cleared up 🎉

2023-08-30 14:37 UTC, sarinapadilla approved these changes
Looks good!

2023-08-30 21:20 UTC, arcepaul commented
Please perform axe Dev Tools scans on the pages.  A new issue is popping up from a duplicated div in the footer.  Look for the id `email-error-message` and it comes up twice.  The div should  not be there at all since I did not try to submit an email.

2023-08-30 21:28 UTC, arcepaul commented
On the promoblocks page, Alter the second title `NCI Annual Plan & Budget Proposal for Fiscal Year 2024 (Dark)`. The `<h2>`s are being used as aria labels and are getting flagged as not being unique any more.

2023-08-30 21:30 UTC, arcepaul commented
Hero images on https://designsystem-dev.cancer.gov/pr-1065/example-site/example-pages/nci-hero.html are now missing

2023-09-05 20:00 UTC, olitharp-nci requested changes
Can you change every instance of "promoblock" to "promo block" and remove "nci" from "nci hero"

2023-09-06 14:09 UTC, olitharp-nci commented on testing/ncids-js-testing/public/example-pages/promoblock-example.html
rename to promo-block-example

2023-09-06 14:24 UTC, karlikpj commented on testing/ncids-js-testing/public/example-pages/nci-cta-strip.html
updated and also added a comment in the commits for this/hero/promo block updates.

2023-09-07 15:17 UTC, arcepaul approved these changes

2023-09-07 15:17 UTC, merged