(#1010)Add border-radius to guidecards w/ img-desc
NCIOCPL/ncids pull request #1091
Opened 2023-07-06 18:10 UTC by arcepaul

Closes #1010 .

Add 4px border radius to guide cards w/ image and description

2023-07-08 16:55 UTC, bryanpizzillo commented on packages/ncids-css/packages/nci-guide-card/internal/_nci-with-image-and-description.scss
> +	.nci-guide-card {
This seems wrong here. The `nci-guide-card--with-image-and-description` is the variant of the `nci-guide-card`. Shouldn't this be `&.nci-guide-card`?

2023-07-10 16:06 UTC, olitharp-nci requested changes

2023-07-12 15:50 UTC, bryanpizzillo approved these changes

2023-07-12 15:53 UTC, dlescarbeau approved these changes

2023-07-14 18:27 UTC, bennettcc approved these changes

2023-07-14 18:27 UTC, bennettcc commented
Approved by product on 7/14 - adding the checkmark on their behalf

2023-07-14 19:24 UTC, bryanpizzillo requested changes

2023-07-14 19:24 UTC, bryanpizzillo commented on packages/ncids-css/packages/nci-guide-card/internal/_nci-with-image-and-description.scss
> +	.nci-guide-card__image {
Please move this back so the diff is cleaner.

2023-07-14 20:00 UTC, bryanpizzillo approved these changes

2023-07-14 20:01 UTC, merged