(#1095) Fixes iOS issue with rounded searchbox
NCIOCPL/ncids pull request #1110
Opened 2023-07-12 18:20 UTC by dlescarbeau

Closes #1095

2023-07-18 11:08 UTC, karlikpj approved these changes

2023-07-18 18:39 UTC, olitharp-nci requested changes

2023-07-18 18:39 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_usa-pagination_button_hover_0_document_1_tablet.png
any ideas why pagination is diffing?

2023-07-19 14:21 UTC, bennettcc commented
Approving on behalf of product - reviewed on 7/18

2023-07-21 16:58 UTC, olitharp-nci approved these changes

2023-07-24 15:15 UTC, sarinapadilla commented
I believe this may be an issue with `usa-input` rather than `nci-autocomplete`. When viewing `nci-autocomplete` in Storybook, there is a small border radius, while on Prod the corners are rectangular like `usa-input`. I'm not sure which of these components is causing the rounded search box.

Unfortunately, I can't see the rounded corner issue in Storybook on an iPad, while I can see it on an ODE. It may be that we need to get this fix on an ODE for testing before we can pass this PR.

2023-07-25 14:36 UTC, andyvanavery approved these changes
Passes Product Review

2023-07-26 14:35 UTC, merged