(#793, #792) NCI Hero with Dark Tagline and Button
NCIOCPL/ncids pull request #1115
Opened 2023-07-14 14:49 UTC by dev-rana-publicis

Closes #793
Closes #792

2023-07-20 14:52 UTC, andyvanavery approved these changes
Passes Product Review.

2023-07-20 14:54 UTC, dlescarbeau approved these changes

2023-07-21 14:50 UTC, karlikpj approved these changes

2023-07-21 14:52 UTC, bennettcc commented
Will demo this to the Feds on Tuesday 7/25 - will wait to merge in until we have their approval

2023-07-21 19:00 UTC, olitharp-nci requested changes

2023-07-21 19:00 UTC, olitharp-nci commented on packages/ncids-css/packages/nci-hero/internal/_nci-hero.scss
> +	&--dark {
is this technically the dark hero variant or the dark cta variant?

2023-07-24 16:14 UTC, olitharp-nci approved these changes

2023-07-25 16:20 UTC, arcepaul approved these changes

2023-07-25 17:50 UTC, merged