(#1107) Create nci header default source
NCIOCPL/ncids pull request #1145
Opened 2023-08-14 20:59 UTC by olitharp-nci

- Create auto init script for nci header
- Create temp default source for mega menu

Closes #1107
Touches #1108
Touches #1106

2023-08-23 02:37 UTC, bryanpizzillo requested changes
Ok, let's talk tomorrow. There are a few things about the autoinit that is slightly off. Also I have a genuine question about the mega menu source.

2023-08-23 02:37 UTC, bryanpizzillo commented on packages/ncids-js/src/components/nci-header/utils/mega-menu/mega-menu-nav.ts
> +			// Programmatically create unique id
There seems to be a need for a update of the unit tests for mega-menu? I assume this is being done in the if to not draw the item if it is null. Although, I don't know where it is drawing either.

2023-08-23 02:37 UTC, bryanpizzillo commented on packages/ncids-js/src/index.ts
> +import { NCIExtendedHeaderWithMegaMenuAutoInit } from './components/nci-header/index';
This should not be in the index. If you:
```
import { NCIExtendedHeaderWithMegaMenu } from './components/nci-header';
```
In something like CGDP, we will be bundling the index.js module. Which means we should also be getting the `NCIExtendedHeaderWithMegaMenuAutoInit` pulled along.

I was thinking that others would do something like:
```
import { NCIExtendedHeaderWithMegaMenu } from '@nciocpl/ncids-js/nci-header/auto-init';
```

2023-08-23 02:37 UTC, bryanpizzillo commented on testing/ncids-js-testing/src/auto-init.ts
> +new NCIExtendedHeaderWithMegaMenuAutoInit();
The idea with the autoinit is that you do not have to execute it. The import should be all you need.

2023-08-23 02:37 UTC, bryanpizzillo commented on packages/ncids-js/src/components/nci-header/utils/auto-init/index.ts
> + * new NCIExtendedHeaderWithMegaMenuAutoInit();
This should be called in this module.

2023-08-31 14:26 UTC, karlikpj approved these changes

2023-09-06 18:07 UTC, bryanpizzillo requested changes
Also, can you creatively organize this into 
* `src/components/nci-header/extended-with-mega-menu/index.ts` - the current header export.
* `src/components/nci-header/extended-with-mega-menu/auto-init/index.ts` - the auto init.

So you would do:
`import header from '@nciocpl/ncids-js/components/nci-header/extended-with-mega-menu`
and
`import '@nciocpl/ncids-js/components/nci-header/auto-init/extended-with-mega-menu';`

2023-09-06 18:07 UTC, bryanpizzillo commented on testing/ncids-js-testing/public/example-pages/auto-init-example.html
> +								href='./../assets/data/mega-menu/example-data-1.html'
Can we either use `javascript:void();` or `#` here?

2023-09-06 18:07 UTC, bryanpizzillo commented on testing/ncids-js-testing/src/auto-init.ts
> +import '@nciocpl/ncids-js/components/nci-header/auto-init/index';
Can't you just drop the `/index` here?

2023-09-07 16:19 UTC, dlescarbeau approved these changes

2023-09-11 14:39 UTC, bryanpizzillo approved these changes
Looks good.

2023-09-11 14:39 UTC, merged