(#1176) List Component Page
NCIOCPL/ncids pull request #1244
Opened 2023-09-19 10:23 UTC by karlikpj

Closes #1176

2023-09-21 15:09 UTC, olitharp-nci requested changes

2023-09-21 15:09 UTC, olitharp-nci commented on docs/content/components/list.mdx
>  <Tabs label="code">
can you kill the tabs on this page

2023-09-28 21:24 UTC, olitharp-nci commented
Blocked by #1234

2023-10-13 14:17 UTC, andyvanavery31 approved these changes
Passes Product review.

2023-10-13 15:46 UTC, olitharp-nci approved these changes

2023-10-13 15:49 UTC, merged