(#1190) Foundations Color Page
NCIOCPL/ncids pull request #1248
Opened 2023-09-19 18:17 UTC by karlikpj

Closes #1190

2023-09-21 13:55 UTC, olitharp-nci approved these changes

2023-09-21 15:33 UTC, bennettcc approved these changes

2023-09-21 15:34 UTC, bennettcc commented
Approved on behalf of product - they reviewed and approved on 9/20

2023-10-04 17:55 UTC, bennettcc commented
This was reverified by product on 10/4 - passes their testing

2023-10-05 14:15 UTC, olitharp-nci requested changes

2023-10-05 14:15 UTC, olitharp-nci commented on docs/content/foundations/color.mdx
make sure this file passes a11y

2023-10-10 15:01 UTC, olitharp-nci requested changes

2023-10-10 15:01 UTC, olitharp-nci commented on docs/content/foundations/color.mdx
![Screenshot 2023-10-10 at 10 01 22 AM](https://github.com/NCIOCPL/ncids/assets/85901679/40955153-9b27-4991-9809-40ae88fff71a)

2023-10-10 20:45 UTC, sarinapadilla commented
@karlikpj we discussed removing the Foundations > Appearance > Color page and only having the Foundations > Color page. If we could include removing that and the removal of the Color link on the Appearance landing page on this PR, that would be great!

2023-10-11 14:54 UTC, andyvanavery31 approved these changes
Passes Product review.

2023-10-13 02:30 UTC, olitharp-nci approved these changes

2023-10-13 02:30 UTC, merged