(#1263) Update Docsite Footer Links
NCIOCPL/ncids pull request #1264
Opened 2023-09-25 08:15 UTC by karlikpj

Closes #1263

2023-09-25 20:13 UTC, bennettcc approved these changes

2023-09-25 20:14 UTC, bennettcc commented
Reviewed and approved by product on 9/25

2023-09-28 16:38 UTC, olitharp-nci requested changes

2023-09-28 16:38 UTC, olitharp-nci commented on docs/content/foundations/appearance/border.mdx
this is the incorrect ticket for these changes

https://github.com/NCIOCPL/ncids/issues/1233

2023-09-29 13:33 UTC, olitharp-nci approved these changes

2023-09-29 14:00 UTC, merged