(#1203) Typography Font Size Family
NCIOCPL/ncids pull request #1265
Opened 2023-09-25 16:29 UTC by karlikpj

Closes #1203

2023-09-29 17:11 UTC, bennettcc approved these changes

2023-10-03 22:10 UTC, olitharp-nci requested changes

2023-10-03 22:10 UTC, olitharp-nci commented on docs/content/foundation/typography/fonts.mdx
what are we doing about the other utility classes from this page? 
https://designsystem.digital.gov/utilities/font-size-and-family/

the sizes for ncids will not match uswds

2023-10-06 16:59 UTC, bennettcc commented
This was re-reviewed by @andyvanavery31 on 10/6 - passes his review and this is ready to be merged from products perspective @karlikpj @olitharp-nci

2023-10-06 17:40 UTC, olitharp-nci approved these changes

2023-10-06 17:40 UTC, merged