(#1270) Disable USWDS Basic Color Tokens
NCIOCPL/ncids pull request #1274
Opened 2023-09-29 16:00 UTC by karlikpj

Closes #1270

2023-10-01 15:20 UTC, karlikpj commented
**_note_**
These three colors will have to remain active as they are used by USWDS in their storybook examples for usa-icon-list.

```
"red": get-system-color("red", 50, "vivid"),
"green": get-system-color("green", 50, "vivid"),
"blue": get-system-color("blue", 50, "vivid"),
```

2023-10-02 15:56 UTC, olitharp-nci commented
> **_note_** These three colors will have to remain active as they are used by USWDS in their storybook examples for usa-icon-list.
> 
> ```
> "red": get-system-color("red", 50, "vivid"),
> "green": get-system-color("green", 50, "vivid"),
> "blue": get-system-color("blue", 50, "vivid"),
> ```

2023-10-02 15:57 UTC, olitharp-nci commented
sorry i didn't mean to click close with comment 💀 

we should discuss this issue

2023-10-02 18:44 UTC, olitharp-nci requested changes

2023-10-02 18:44 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-icon-list/src/index.scss
> +	color: #e52207; //red-vivid-50
you should still be able to use the `color` mixin with token values instead of hard coding

2023-10-02 20:55 UTC, olitharp-nci approved these changes

2023-10-03 15:31 UTC, bennettcc commented
Product review not needed - tech review only required for this PR

2023-10-04 00:27 UTC, merged