(#1324) Fix link path on Template Page
NCIOCPL/ncids pull request #1341
Opened 2023-10-18 19:55 UTC by karlikpj

Closes #1324

2023-10-19 14:32 UTC, bennettcc approved these changes

2023-10-19 15:23 UTC, dlescarbeau requested changes

2023-10-19 15:23 UTC, dlescarbeau commented on docs/content/templates/index.mdx
> +### [3-Card Row](/templates/feature-card-row)
Should be `/templates/3-card-row`

2023-10-19 17:12 UTC, dlescarbeau approved these changes

2023-10-20 14:09 UTC, arcepaul approved these changes

2023-10-20 14:10 UTC, arcepaul commented on docs/content/templates/index.mdx
> +### [3-Card Row](/templates/3-card-row)
wait, shouldn't it just be `./3-card-row` ?

2023-10-20 16:28 UTC, merged