(#1150) Adds custom nci-heading classes
NCIOCPL/ncids pull request #1356
Opened 2023-10-25 16:27 UTC by dlescarbeau

Closes #1150

2023-10-25 18:58 UTC, olitharp-nci requested changes

2023-10-26 14:30 UTC, dlescarbeau commented on packages/ncids-css/packages/nci-heading/internal/_nci-heading.scss
> +		&--label {
So should it be `.nci-heading--label-h1` in that case? I was under the impression this class would look something like `.nci-heading-h1--label`

2023-10-26 14:32 UTC, dlescarbeau commented on packages/ncids-css/packages/nci-heading/internal/_nci-heading.scss
> +		&--label {
Or should it just be multiple classes IE `.nci-heading-h1 .nci-heading--label` ? I did see that comment, I hadn't gotten around to using typeset yet as this was still a draft :)

2023-10-27 18:23 UTC, karlikpj approved these changes

2023-11-06 15:10 UTC, olitharp-nci commented on packages/ncids-css/packages/nci-heading/internal/_nci-heading.scss
> +@mixin nci-heading($headingSize) {
use 

```scss
@include typeset-display;
@include typeset-h1;
... etc
```

as requested in the comment linked earlier

2023-11-06 15:15 UTC, olitharp-nci commented on docs/content/foundations/typography/headings.mdx
> +		<h1 class="nci-heading--display">nci-heading--display</h1>
```suggestion
		<h1 class="nci-heading-display">nci-heading-display</h1>
```

2023-11-08 21:22 UTC, bennettcc approved these changes

2023-11-08 21:23 UTC, bennettcc commented
Passed by product on 11/8

2023-11-13 21:00 UTC, olitharp-nci requested changes

2023-11-13 21:00 UTC, olitharp-nci commented on packages/ncids-css/packages/nci-heading/internal/_nci-heading.scss
> +.nci-heading-display {
duplicated below?

2023-11-13 21:09 UTC, olitharp-nci requested changes

2023-11-13 21:09 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/design-tokens/typography/fonts/fonts.scenarios.js
> +				label: 'tablet',
from the scss media queries we need a test for default (mobile) and tablet-lg. I'm seeing desktop and tablet on this file being generated too. is this supposed to be mobile and are both desktop breakpoints supposed to be tablet-lg?

2023-11-16 15:40 UTC, olitharp-nci approved these changes

2023-11-16 16:15 UTC, arcepaul approved these changes

2023-11-16 16:15 UTC, merged