(#1149) NCIDS Collections
NCIOCPL/ncids pull request #1384
Opened 2023-11-01 20:08 UTC by dev-rana-publicis

Closes #1149

2023-11-13 20:57 UTC, olitharp-nci requested changes
Still need to create an additional test case to show the requested html for media.

2023-11-13 20:57 UTC, olitharp-nci commented on packages/ncids-css/patches/@uswds+uswds+3.3.0.patch
> ++$collection-calendar-img-margin: 2;
can you rename this to `collection-calendar-margin` so we don't confuse it with the img block

2023-11-28 19:48 UTC, karlikpj approved these changes

2023-11-29 20:27 UTC, andyvanavery31 approved these changes
Passes Product review.

2023-12-01 07:13 UTC, merged