(#773) Fix Stylelint Config
NCIOCPL/ncids pull request #1386
Opened 2023-11-03 17:54 UTC by karlikpj

Closes #773

2023-11-03 19:14 UTC, karlikpj commented
Developer note - don't put comments after selectors. Comments must be above the class block.
```	
/* bad example */
.class {			
  'after', // position
  '05', // margin, units()
  }
```

```	
/* good example */
/* position &   margin, units() */
.class {			
  'after',
  '05',
  }
```

2023-11-13 16:23 UTC, olitharp-nci requested changes

2023-11-13 16:23 UTC, olitharp-nci commented on packages/ncids-css/.stylelintrc.js
> +		'no-duplicate-selectors': null,
Remove 
`'unit-no-unknown': null,`
`''no-duplicate-selectors': null,`

2023-11-13 16:23 UTC, olitharp-nci commented on packages/ncids-css/.stylelintrc.js
> +		'no-duplicate-selectors': null,
i'll update the ticket here shortly

2023-11-13 16:32 UTC, olitharp-nci requested changes

2023-11-13 16:32 UTC, olitharp-nci commented on packages/ncids-css/packages/nci-autocomplete/internal/_nci-autocomplete.scss
> +		.min-placeholder-message {
Please add a note in the commit that you are changing the classname that affects javascript for autocomplete and that you've updated tests that go along with it

2023-11-13 17:35 UTC, olitharp-nci approved these changes

2023-11-13 20:52 UTC, arcepaul approved these changes

2023-11-13 20:52 UTC, merged