(#653) extends usa-banner
NCIOCPL/ncids pull request #1394
Opened 2023-11-13 18:51 UTC by dlescarbeau

Closes #653

2023-11-17 18:53 UTC, karlikpj approved these changes

2023-11-20 22:52 UTC, olitharp-nci requested changes
just one thing i'm seeing right now... additionally we might want to consider renaming the scenario files to "usa-banner" as well since those are still called "nci-banner". we can discuss later if we want to do that since it should trigger a product review changing the regression images. that one isn't a make or break it for me

2023-11-20 22:52 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-banner/nci-banner.scss
can you rename this file to usa-banner.scss

2023-11-21 17:11 UTC, dlescarbeau commented on testing/ncids-css-testing/stories/components/usa-banner/nci-banner.scss
best i can do is banner.scss

2023-11-21 20:23 UTC, olitharp-nci approved these changes

2023-11-21 20:23 UTC, merged