(#580) Adds styles for buttons with icons
NCIOCPL/ncids pull request #1404
Opened 2023-11-27 19:16 UTC by dlescarbeau

- Closes #580

2023-11-30 22:31 UTC, bennettcc approved these changes

2023-12-04 20:51 UTC, arcepaul approved these changes

2023-12-04 21:10 UTC, olitharp-nci requested changes

2023-12-04 21:25 UTC, olitharp-nci approved these changes

2023-12-04 21:46 UTC, olitharp-nci commented
Documentation will be updated in #1411

2023-12-04 21:47 UTC, merged