(#1232) Patch Sidenav to Default
NCIOCPL/ncids pull request #1459
Opened 2024-01-02 18:13 UTC by karlikpj

Closes #1232

2024-01-10 15:43 UTC, bennettcc approved these changes

2024-01-10 15:43 UTC, bennettcc commented
Approved by product as of 1/9

2024-01-12 16:13 UTC, olitharp-nci requested changes

2024-01-12 16:13 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-sidenav/nci-sidenav.scss
> +@use "styles/ncids";
this should also be @forward

2024-01-17 15:36 UTC, merged