(#1478) Error State Color
NCIOCPL/ncids pull request #1510
Opened 2024-01-31 19:13 UTC by karlikpj

Closes #1478

2024-02-07 15:55 UTC, blilianyu commented
On Form Elements, can we:
- make the background on the error message span the width of the input field
- add padding on the text so it's not touching
- add the background so it's touching/around the input field?

<img width="688" alt="Screenshot 2024-02-07 at 10 53 26 AM" src="https://github.com/NCIOCPL/ncids/assets/51677926/395a6732-acb8-4baa-9900-62e431d73d3f">

2024-02-07 16:10 UTC, karlikpj commented
@blilianyu We can add padding  - however the error message itself is a separate element from the input (which could be a select / text / radio) and there is no consistent container that wraps them both in the HTML that would they red background to encompass the message and form control.
![Screenshot 2024-02-07 at 11 08 54 AM](https://github.com/NCIOCPL/ncids/assets/66697447/08699760-1d0e-4f7e-9d0d-588004af12af)

2024-02-07 16:24 UTC, blilianyu commented
@karlikpj ok, then can we remove the margin so the error message is touching the input field?

2024-02-07 20:10 UTC, blilianyu commented
@karlikpj updates look good! I would like to change the input field width to be 100% but noting that this change would be a separate ticket.

2024-02-08 16:27 UTC, blilianyu commented
Updates on form field and the other error states look good! I've opened a CR #1520 for updating the input field width.

2024-02-09 15:18 UTC, arcepaul commented
Looks like there is some right padding needed in the box
<img width="264" alt="error-box" src="https://github.com/NCIOCPL/ncids/assets/45469809/3ccd8a69-5fc5-4cd2-8962-d6be893c53a5">

2024-02-12 19:20 UTC, blilianyu commented
Updates look good to me!

2024-02-13 14:26 UTC, olitharp-nci requested changes

2024-02-13 14:26 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/forms/form-elements/form-elements.stories.js
> +export const Elements = () => <TestCase css={css} html={Template.bind({})()} />;
Can you make sure this story matches the outline Bryan provided in the comment here
https://github.com/NCIOCPL/ncids/issues/1478#issuecomment-1922156326

2024-02-13 20:58 UTC, olitharp-nci approved these changes

2024-02-14 15:14 UTC, olitharp-nci approved these changes

2024-02-14 15:23 UTC, sarinapadilla approved these changes
Looks good!

2024-02-14 15:25 UTC, merged