(#1402) Fix Sass Imports on Docsite Content
NCIOCPL/ncids pull request #1530
Opened 2024-02-15 17:11 UTC by karlikpj

Closes #1402

2024-02-21 15:34 UTC, sarinapadilla requested changes

2024-02-21 15:34 UTC, sarinapadilla commented on docs/content/components/banner.mdx
> +    /* This packages should also be imported in your sass stylesheet if not already as Banner with Language Toggle is dependent on it. */
Is this supposed to be "This package" or "These packages"?

2024-02-22 18:06 UTC, sarinapadilla approved these changes
Looks good!!

2024-02-22 18:59 UTC, olitharp-nci approved these changes

2024-02-22 18:59 UTC, merged