Ticket/474 update header test coverage
NCIOCPL/ncids pull request #1543
Opened 2024-02-22 16:32 UTC by dlescarbeau

- Closes #474

2024-02-23 18:21 UTC, bennettcc approved these changes

2024-02-23 18:21 UTC, bennettcc commented
Sarina reviewed on 2/23 - passed on behalf of product

2024-02-29 16:49 UTC, olitharp-nci requested changes

2024-02-29 16:49 UTC, olitharp-nci commented on package.json
> +		"jsdom-testing-mocks": "^1.11.0",
Use a tilde (~) here instead of a caret (^) so we can maintain the package version. 

This dependency should live in ncids-js instead.

2024-02-29 16:49 UTC, olitharp-nci commented on package.json
> +		"jsdom-testing-mocks": "^1.11.0",
Oh and please correct this commit title and Closes # to point to the correct ticket.

2024-02-29 16:49 UTC, olitharp-nci commented on packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts
> +	public activeMenu!: boolean;
move back to protected, we don't need property public

2024-02-29 17:56 UTC, olitharp-nci approved these changes

2024-02-29 18:00 UTC, merged