(#1578) Update Banner Storybook
NCIOCPL/ncids pull request #1611
Opened 2024-03-19 20:04 UTC by karlikpj

Closes #1578

2024-03-20 18:09 UTC, olitharp-nci requested changes

2024-03-20 18:09 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_usa-banner_default_spanish_0_document_1_mobile-lg.png
I only see media queries for the tablet breakpoint in the css. There should only be mobile and tablet regression images for all of banner. Remove any extra from previously existing banner regression images.

2024-03-21 17:19 UTC, andyvanavery31 commented
Looks good to me! Tested on Chrome, FF, and Safari

2024-03-21 18:15 UTC, andyvanavery31 approved these changes
Passes product review.

2024-04-02 13:58 UTC, olitharp-nci approved these changes

2024-04-02 14:30 UTC, merged