(#1582) Update Collections Storybook
NCIOCPL/ncids pull request #1612
Opened 2024-03-20 18:12 UTC by karlikpj

Closes #1582

2024-03-21 20:01 UTC, andyvanavery31 commented
@karlikpj Please change the name of the variant from "Only Headers" to "Condensed" and remove the USWDS pass through test cases

2024-04-05 15:24 UTC, andyvanavery31 requested changes
Can you please update the "Headers Only" name to be "Condensed" in the "Variants" folder?

For the regression images, can you please investigate the following?

- For the calendar, I am seeing 2 changes occurring due to breakpoints:
  - The calendar icon changes size between tablet and tablet large (879px to 880px) but the `ncids_nci-collection_calendar_mobile_size_0_document_0_tablet-lg.png` shows the smaller icon, but tablet large should have the same icon size as desktop. Not sure if this is a naming issue of the file or if we need to grab a different image.
  - The text of the title and body text starts reducing the width of its wrapping inside the tablet breakpoint (I'm seeing it start at 788px/789px). Do we need all images of breakpoints smaller than where this begins, or is having just Mobile sufficient
- Can you update the names regression image files for consistency? I'll defer to your judgement on naming, but things I'm seeing are:
  - `ncids_usa-collection_calendar_0_document_0_mobile.png` vs `ncids_usa-collection_calendar_desktop_size_0_document_0_desktop.png` vs `ncids_usa-collection_caledar_mobile_size_0_document_0_tablet-lg.png` (for other stories they were all in the form of the first one)
  - `ncids_usa-collection_media_0_document_0_mobile.png` vs ncids_usa-collection_media_image_not_visible_0_document_0_tablet-lg.png` vs `ncids_usa-collection_media_image_visible_0_document_0_desktop.png` (I'm not sure what would be best, I like the first one, but having the indication of the media image showing vs not showing is nice because of the breakpoints)
- Can you update the name of the regression image for `ncids_usa-collection_only_headers_0_document_0_mobile.png` to `ncids_usa-collection_condensed_0_document_0_mobile.png`

2024-04-05 17:26 UTC, karlikpj commented
@andyvanavery31 there is a miss size in a breakpoint or two from the original file / fixing that - and that should rename to the correct size/ test case names

2024-04-16 12:53 UTC, andyvanavery31 requested changes
Could you please update the Variants > Only Headers to Variants > Condensed? And ensure that the naming of the images reflects that change?

2024-04-16 14:59 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-17 13:58 UTC, olitharp-nci requested changes
> - [ ] Add collection passthrough (exact copy of what we had before)
> - [x] Remove USWDS test cases from NCIDS collection

These tasks on the ticket were not done. We can talk about it. @bryanpizzillo @sarinapadilla @andyvanavery31

2024-04-24 14:36 UTC, olitharp-nci requested changes

2024-04-24 14:36 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-collection/src/usa-collection.scenarios.js
> +		focusSelector: '.usa-link',
if there are no styles for usa-link in usa-collections, we do not need this many tests for usa-link. usa-link shoud be tested in usa-link.

2024-04-29 16:29 UTC, olitharp-nci approved these changes

2024-04-29 17:03 UTC, merged