(#1580) Update Storybook Buttons
NCIOCPL/ncids pull request #1614
Opened 2024-03-21 17:39 UTC by karlikpj

Closes #1580

2024-03-27 19:31 UTC, bryanpizzillo requested changes
Can you please move the "Outline Inverse" label outside of the dark background?

2024-04-05 14:26 UTC, bennettcc commented
@bryanpizzillo this one looks like its ready for your re-review please

2024-04-05 16:05 UTC, bryanpizzillo requested changes
@sarinapadilla, @andyvanavery31  and @olitharp-nci - I remember discussing that we need to have tests for icons as Big and Small. We should have it, but IDC if the use cases are added to big/small, or if big/small is added to the icon left/right. Also we definitely need tests for icon when it is full width (left and right). (The reason we definitely need them is that we had missed this once before and it caused https://github.com/NCIOCPL/cgov-digital-platform/issues/4242)

Additionally, we probably do not need all the different breakpoints for the buttons, unless there is some specific thing in that variant/modifier. Or for example, just put breakpoints on the default if there is something special with button, but not on all the other size/outline modifiers, for example.

2024-04-05 19:04 UTC, andyvanavery31 commented
@bryanpizzillo @olitharp-nci @sarinapadilla I think that trying to do them all inside the Modifiers could get confusing, so how about we make a subfolder within the Test Cases folder that is something like "Modifier Combinations". Then inside of it we can hit all the permutations we need to test, and for each one we put all the themes (Primary, Secondary, Accent Cool, Accent Warm, Base, Outline, Outline Inverse):

- Full Width Icon Left Anchor
- Full Width Icon Right Anchor
- Full Width Icon Left Button
- Full Width Icon Right Button
- Big Icon Left Anchor
- Big Icon Right Anchor
- Big Icon Left Button
- Big Icon Right Button
- Small Icon Left Anchor
- Small Icon Right Anchor
- Small Icon Left Button
- Small Icon Right Button

I also agree about what you said with the regression images

2024-04-05 20:18 UTC, karlikpj commented
Icon buttons need at least desktop / mobile as the icon should stick to the  left or right side as the button snaps goes to full width at mobile. otherwise the rest can just be the default viewport size.

2024-04-08 14:56 UTC, bryanpizzillo commented
> * Full Width Icon Left Anchor
> * Full Width Icon Right Anchor
> * Full Width Icon Left Button
> * Full Width Icon Right Button
> * Big Icon Left Anchor
> * Big Icon Right Anchor
> * Big Icon Left Button
> * Big Icon Right Button
> * Small Icon Left Anchor
> * Small Icon Right Anchor
> * Small Icon Left Button
> * Small Icon Right Button

Let's just add these to the big and small pages like we did for unstyled. We only need the primary icon color, as the icon page has all the other colors.

2024-04-08 18:09 UTC, andyvanavery31 commented
@karlikpj I updated the ticket so that it includes the "Icon Left Primary" and "Icon Right Primary" on the Big, Small, and Full Width Pages (both anchor and button). Please add those cases to those pages, and while you're making changes, can you please change the folder name "FullWidth" to "Full Width" (in the Modifiers folder), and change the "TestCases" folder name to "Test Cases".

Cc: @bryanpizzillo @olitharp-nci @sarinapadilla

2024-04-16 12:49 UTC, andyvanavery31 requested changes
`ncids_usa-button_nci-full-width_anchor_0_document_0_desktop.png`,  `ncids_usa-button_nci-full-width_button_0_document_0_desktop.png`, and `ncids_usa-button_unsuported_outline_color_0_document_0_mobile-lg.png` are giving a "Couldn't find story matching..." error. Could you please fix them?

2024-04-16 15:06 UTC, andyvanavery31 commented
It looks like `ncids_usa-button_unsuported_outline_color_0_document_0_mobile-lg.png`  got changed to `ncids_usa-button_testcases_unsuported_outline_color_0_document_0_mobile-lg.png` and is now throwing the same error. Could you check it? @karlikpj

2024-04-16 17:52 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-17 15:32 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-button/usa-button.scss
> +.section-header {
let's chat

2024-04-17 15:40 UTC, olitharp-nci requested changes
Full width buttons with icons does missing disabled state

2024-04-23 15:17 UTC, olitharp-nci commented
# Button component known issues

1. **Icon buttons do not emulate USWDS Button Icons.** Button icons need to be corrected to match USWDS as per the initial request. Additional requirements needed by design should possibly be an NCI variant. Consider creating button icons as a separate component to align with other design systems.
2. **Button documentation page needs a revamp.** We had a meeting in the past about issues with the documentation page missing, incorrect, or confusing information, and now it is worse.
   1.  No documentation on external links
   2. No documentation on buttons with icons
   3. Code snippets only exist for the default and secondary buttons
   5. We should not be highlighting `usa-button--hover` `usa-button--active` and `usa-focus` in code snippets. These classes should be visual only.
   6. Variations are wrong
   7. Modifications are wrong
   
8. **The NCI variant small button should not have left and right padding.** See storybook example where the small button is the only in the list to have extra padding. The button should function exactly as all other like buttons.

2024-04-30 15:06 UTC, bennettcc commented
Per 4/30 standup - known issues #1-3 will be created into another story. Item #4 will be created into another story.

All are nice to haves for NCIDS launch (can sit at the bottom of the NCIDS Launch backlog

@andyvanavery31

2024-04-30 18:57 UTC, andyvanavery31 requested changes
Can you please update all the regression images so that there are two images per story:
1. Mobile breakpoint
2. Tablet Lg breakpoint

These will cover the button going full width at mobile and will show them in their "normal" view without wrapping.

2024-05-02 17:05 UTC, bryanpizzillo requested changes
One issue in a package.json and also the following:

Full width icon left looks broken:
<img width="624" alt="image" src="https://github.com/NCIOCPL/ncids/assets/11215649/0cc21898-becf-43b1-b891-6ecb2d0162b9">
https://designsystem-dev.cancer.gov/pr-1614/storybook/?path=/story/components-button-modifiers-icon-icon-left--anchor

https://designsystem-dev.cancer.gov/pr-1614/storybook/?path=/story/components-button-modifiers-icon-icon-left--button

Also shouldn't this have a title with "unstyled" in it?

2024-05-02 20:32 UTC, olitharp-nci commented on testing/ncids-css-testing/package.json
> +	"version": "2.6.0",
tis

2024-05-02 21:19 UTC, bryanpizzillo approved these changes
Looks good

2024-05-03 17:10 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-05-06 19:16 UTC, arcepaul approved these changes

2024-05-06 19:18 UTC, merged