(#1468) JS for accordion functionality
NCIOCPL/ncids pull request #1616
Opened 2024-03-25 14:45 UTC by dlescarbeau

Closes #1468

2024-03-26 18:55 UTC, andyvanavery31 commented
Looks good to me!

2024-03-26 18:55 UTC, andyvanavery31 approved these changes

2024-03-28 15:50 UTC, olitharp-nci requested changes

2024-03-28 15:50 UTC, olitharp-nci commented on docs/content/components/accordion.mdx
> +    | Bordered Accordion | Use the boarded accordion to add a border to the panels of your accordion. |
bordered

2024-03-28 15:50 UTC, olitharp-nci commented on docs/content/components/accordion.mdx
> +code_snippets:
You need documentation about auto init here. See header.

2024-03-28 16:51 UTC, olitharp-nci approved these changes

2024-03-28 17:42 UTC, merged