(#1579) Breadcrumb storybook reorganization
NCIOCPL/ncids pull request #1621
Opened 2024-03-28 05:57 UTC by arcepaul

Closes #1579

- file renaming and re-organization

2024-04-05 14:23 UTC, andyvanavery31 requested changes
Could you please update the test cases to have the names "Default with Very Long Content" and "Wrap with Very Long Content" and update those two stories with the long breadcrumbs. Then could you also please update the reference images with those stories at the different breakpoints?

2024-04-16 18:01 UTC, andyvanavery31 requested changes
Can you please change the contents of the breadcrumb Test Cases of "Default with Very Long Content" and "Wrap with Very Long Content" to use the following breadcrumb: (as seen on [this page](https://www.cancer.gov/grants-training/grants-funding/funding-opportunities/oia/award-recipients/2022)

"Home > Grants & Training > Research Grants > Research Funding Opportunities > Outstanding Investigator Award > Award Recipients > 2022 NCI Outstanding Investigator Award Recipients". 

And then can you please make sure the regression images are updated with this change?

2024-04-18 21:59 UTC, olitharp-nci requested changes

2024-04-18 21:59 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-breadcrumb/usa-breadcrumb--default.twig
> +				<span>Home</span>
Don't hardcode content - pass them through params

2024-04-19 15:10 UTC, olitharp-nci requested changes

2024-04-19 15:10 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-breadcrumb/content/usa-breadcrumb--extra-long-content.json
> +			"label": "Award Recipients",
https://github.com/NCIOCPL/ncids/pull/1621#pullrequestreview-2004298462

2024-04-23 17:21 UTC, olitharp-nci requested changes

2024-04-23 17:21 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-breadcrumb/usa-breadcrumb.default.stories.js
> +	<TestCase css={css} html={Template.bind({})(DefaultVeryLongContent)} />
Well there's no point in the test case for very long content if everything has very long content.

2024-04-23 17:21 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-breadcrumb/usa-breadcrumb.scenarios.js
> +				label: 'tablet',
There's only a breakpoint for mobile-lg in the scss. I'm not seeing a patch for $theme-breadcrumb-min-width to tablet.

1. Default.
2. Any breakpoints found in css or html classes
3. Larger screens if only they make sense for testing.

Replace tablet with mobile-lg.

2024-04-23 17:21 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-breadcrumb/usa-breadcrumb.scenarios.js
> +				width: 880,
Desktop is not 880 it is 1024.

2024-04-24 19:50 UTC, andyvanavery31 commented
@arcepaul Default With Very Long Content in Test Cases is wrapping and it shouldn't. could you please that story and please update the regression images to have the correct images matching the names? We should have 

- Default at Mobile, Mobile Large, Tablet, Desktop
- Wrap at Mobile, Mobile Large, Tablet, Desktop
- Default Very Long at Mobile, Mobile Large, Tablet, Desktop
- Wrap Very Long at Mobile, Mobile Large, Tablet, Desktop

2024-04-29 17:11 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-05-01 14:22 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-05-01 16:34 UTC, olitharp-nci approved these changes

2024-05-01 16:35 UTC, merged