(#1581) Card Storybook Update
NCIOCPL/ncids pull request #1622
Opened 2024-03-28 11:03 UTC by karlikpj

Closes #1581

2024-04-03 20:02 UTC, andyvanavery31 requested changes
Could you please change the icon of Default, and Test Cases to have a folder instead of the 2x2 grid? Could you also please add a space in "TestCases"?

For regression image redundancies:

- ncids_nci_card_active_0_document_0_widescreen.png and ncids_nci-card_focus_0_document_0_widescreen.png

2024-04-04 17:46 UTC, karlikpj commented
The Icon's are via storybook and how the paths/folders are created. The end sections will always be a grid currently.

2024-04-04 20:21 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-16 15:08 UTC, olitharp-nci requested changes

2024-04-16 15:08 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card.twig
> +		<div class="usa-prose">
The twig file should **only** be the card itself. All the content that belongs to the story to help with testing needs to live in the storybook files.

2024-04-16 15:08 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-card/nci-card.scenarios.js
>  		postInteractionWait: 500,
can you change `postInteractionWait` to `readySelector` on all of these that have it. An arbitrary number will slow down the tests

2024-04-16 15:08 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-card/nci-card.testcases.group.without.description.stories.jsx
> +import React from 'react';
Merge all test cases to one story file. Get rid of float. You can create a twig file here that calls the ncids-twig package. The params that are being passed to the twig should only be things that are actually a part of the card component

2024-04-17 13:33 UTC, olitharp-nci requested changes

2024-04-17 13:33 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card.twig
> +	<a href="#" aria-label="Card">
links labels should not be hardcoded either

2024-04-17 13:33 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-card_default_0_document_3_desktop.png
were the margins supposed to change on these or did some classes get moved to the wrong element?

2024-04-18 17:02 UTC, olitharp-nci requested changes

2024-04-18 17:02 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card-group.twig
> +                <a href="#" aria-label="{{ ariaLabel }}">
don't hard code href

2024-04-18 17:02 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card-group.twig
> +                        <img src="{{ item.imageSrc }}" />
add missing alts

2024-04-18 17:02 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card.twig
> +		<a href="#" aria-label="{{ ariaLabel }}">
hardcoded href

2024-04-18 17:02 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-card/nci-card.twig
> +				<img src="{{ imageSrc }}"/>
missing alt

2024-04-19 15:02 UTC, olitharp-nci requested changes

2024-04-19 15:02 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-card/nci-card.group.default.stories.jsx
This should be exported in testing/ncids-css-testing/stories/components/nci-card/nci-card.default.stories.jsx

2024-04-24 18:45 UTC, andyvanavery31 commented
@karlikpj I'm seeing something weird happening with the Test Case of Card Group Without Description, the first card is shrinking the height of the image so it is shorter than the rest, but this is not happening with the Default > Card Group. Also, this is not showing up on the regression images. The regression images look good as long as they are aligned with whatever this fix is.

2024-04-29 18:06 UTC, andyvanavery31 commented
@karlikpj can you please return the description to the default card? I believe that should be the default. Additionally, I am seeing the difference between the left-most card and the rest of the cards got even more obvious when looking at Card Group (works correctly) vs Test Cases > Card Group Without Description (first card's image got really small and the spacing between the left-most and middle card increased)

2024-04-30 13:31 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-05-01 16:41 UTC, olitharp-nci approved these changes

2024-05-01 19:29 UTC, merged