(#1583) CTA Strip Storybook Update
NCIOCPL/ncids pull request #1623
Opened 2024-03-28 16:07 UTC by karlikpj

2024-04-04 17:43 UTC, karlikpj commented
Q1 - we dont show any padding in the docsite/example code so Id opt not to do that in the regression images.
Q2 - each of those breakpoints has something different tablet switches the css to display:block and we have different padding in each
```
	@include at-media('mobile-lg') {
		padding: units(2.5) units(10);
	}

	@include at-media('tablet') {
		padding: units(2) units('card');
	}

	@include at-media('tablet-lg') {
		padding: units(2) units(10);
	}

	@include at-media('desktop') {
		padding: units(2) units(6);
	}
	```

2024-04-15 21:12 UTC, olitharp-nci requested changes

2024-04-15 21:12 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-cta-strip/nci-cta-strip.testcases.long.stories.jsx
> +export default {
Each story does not need it's own story file. You can combine long and spanish into one.

2024-04-15 21:12 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-cta-strip/nci-cta-strip.scenarios.js
You can remove "widescreen" from regression checks, there are no media queries for widescreen.

2024-04-16 15:21 UTC, olitharp-nci approved these changes

2024-04-16 15:42 UTC, merged