(#1586) Guide Card Storybook Update
NCIOCPL/ncids pull request #1628
Opened 2024-04-01 16:05 UTC by karlikpj

Closes #1586

2024-04-03 19:44 UTC, andyvanavery31 requested changes
Could you please fix the following?

- Update the icons of the "Default", "Test Cases", and "Variants" folders to have the folder icon
- Reorganize the primary subfolders to be Default, Variants, then Test Cases
- Add the "Guide Card with Image and Description" subfolder within the "Variants" folder
- Re-name and reorder the individual items in this to match those listed in the ticket

Could you investigate the following possible redundant regression images and remove ones that you confirm are redundant?
- ncids_nci-guide-card_default_0_document_3_desktop.png and ncids_nci-guide-card_default_0_document_4_widescreen.png
- ncids_nci-guide-card_test-case_with-description-and-without-image_0_document_3_desktop.png and ncids_nci-guide-card_test-case_with-description-and-without-image_0_document_4_widescreen.png
- ncids_nci-guide-card_test-case_with-image-and-without-description_0_document_3_desktop.png and ncids_nci-guide-card_test-case_with-image-and-without-description_0_document_4_widescreen.png
- ncids_nci-guide-card_with-image-and-description_default_0_document_3_desktop.png and ncids_nci-guide-card_with-image-and-description_default_0_document_4_widescreen.png

2024-04-04 19:49 UTC, andyvanavery31 commented
Last three minor changes: 

1. Can you add a space between "GuideCard with Image and Description" folder that is inside the "Variants" folder?
2. Can you remove the space between "With Out" that is in the story title "Single Card With Image And Description With Out Heading" which is inside the "GuideCard with Image and Description" folder inside "Variants"?
3. Can you make all instances of "With", "Without", and "And" all lowercase? (i.e. change "Title Aligned Card Group Without Description" to "Title Aligned Card Group without Description")

2024-04-05 12:30 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-16 15:18 UTC, olitharp-nci requested changes
This has the same notes from card

2024-04-18 16:59 UTC, olitharp-nci requested changes

2024-04-18 16:59 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-guide-card_default_0_document_1_tablet.png
the paddings changing on all of these are concerning -- are these expected changes?

2024-04-18 16:59 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-guide-card_variants_with-image-and-description_title-aligned_card-group_0_document_3_desktop.png
fix these?

2024-04-19 14:52 UTC, olitharp-nci requested changes
nci-guide-card.testcases.title.aligned.group.without.description.stories.jsx

these file names are outta pocket try the following

2024-04-19 14:52 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-guide-card/nci-guide-card.testcases.description.without.image.stories.jsx
* nci-guide-card.default.jsx
  * `title: 'components/Guide Card/Default',`
  * `export const Default ...`
  * `export const CardGroup ...`
* nci-guide-card.variants.jsx
  * `title: 'components/Guide Card/Variants/Guide Card With Image and Description',`
  * `export const SingleGuideCardWithImageAndDescriptionWithoutHeading ...`
  * `export const TitleAlignedCardGroup ...`
* nci-guide-card.test-cases.jsx
  * `title: 'components/Guide Card/Test Cases',`
  * `export const GuideCardWithImageAndDescriptionWithoutDescription ...`
  * `export const Guide with Image and DescriptionWithoutImage ...`
  * `export const TitleAlignedCardGroupWithoutDescription ...`
  * `export const TitleAlignedCardGroupWithoutImage ...`

(who named these variants)

2024-04-19 14:56 UTC, olitharp-nci requested changes

2024-04-19 14:56 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-guide-card_default_0_document_2_tablet-lg.png
The spacings are changing so much on these we either need design to approve or something in the template needs to be adjusted so there are less regressions @blilianyu

2024-04-23 21:29 UTC, olitharp-nci requested changes
@andyvanavery31 please review the regressions.

2024-04-24 18:57 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-30 15:10 UTC, andyvanavery31 commented
Please update the padding/spacing of the guide cards to match Prod @karlikpj

2024-05-02 13:47 UTC, andyvanavery31 approved these changes
The stories and regression images match prod. Looks good to me!

2024-05-14 16:15 UTC, olitharp-nci commented
Changes for quick merge: https://github.com/NCIOCPL/ncids/compare/6ba5e783cb334fbf4130cf68519fdca7860d345b..d2ee444cb8317335f477876e38828f2457e76df2
* This compare also includes the rebase, so it hard to tell the changes, which include basic formatting again. It appears to be an ongoing issue for twig files. I will add a ticket to look into missing linting in twig files.

2024-05-14 16:38 UTC, olitharp-nci approved these changes

2024-05-14 16:38 UTC, merged