(#1588) Hero Storybook Update
NCIOCPL/ncids pull request #1630
Opened 2024-04-03 15:05 UTC by karlikpj

Closes #1588

2024-04-05 13:05 UTC, andyvanavery31 requested changes
Can you please change the "Default" story to be "Without Button" the one that exists in the "Default" folder?

2024-04-05 15:34 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-04-15 21:05 UTC, olitharp-nci requested changes
Update the files to use the correct file structure so we can update to the newest version of Storybook.

1. Only stories should have .stories.ts extension.
2. Group items in their respective stories.
3. You may use json if content gets repetitive. 

* testing/ncids-css-testing/stories/components/nci-hero/src/usa-hero.default.stories.js
  * contains: 
     * `export const DefaultWithoutButton`
     * `export const DefaultWithButton`
* testing/ncids-css-testing/stories/components/nci-hero/src/usa-hero.modifiers.stories.js
  * contains: 
     * `export const DarkWithoutButton`
     * `export const DarkWithButton`
* testing/ncids-css-testing/stories/components/nci-hero/src/usa-hero.variants.stories.js
  * contains: 
     * `export const WithCTAStrip`
* testing/ncids-css-testing/stories/components/nci-hero/src/usa-hero.test-cases.stories.js
  * contains: 
     * `export const WithCTALong`
     * `export const withCTASpanish`

Refer to the ones recently merged such as Combo Box, Accordion, or the USWDS passthroughs

2024-04-16 15:26 UTC, olitharp-nci requested changes

2024-04-16 15:26 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-hero/nci-hero.modifiers.stories.jsx
> +export * from "./dark.stories";
Same note here, `export *  from..` breaks the upgrade - change these to the `export const NamedComponent...` from the other examples

change for all

2024-04-17 13:52 UTC, olitharp-nci requested changes

2024-04-17 13:52 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-hero/nci-hero.twig
> +		<img src="{{ image.mobile }}" alt=""/>
add alt to params

2024-04-17 13:52 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-hero_modifiers-dark_without-button_0_document_0_mobile.png
don't think these were supposed to change?

2024-04-17 13:52 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-hero/nci-hero.modifiers.stories.jsx
> +		"image": {
single quotes

2024-04-17 18:22 UTC, karlikpj commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-hero_modifiers-dark_without-button_0_document_0_mobile.png
oops my bad, forgot the modifier class

2024-04-18 16:55 UTC, olitharp-nci requested changes

2024-04-18 16:55 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-hero/nci-hero.twig
> +		<img src="{{ image.mobile }}" alt=""/>
```suggestion
		<img src="{{ image.mobile }}" alt="{{ image.alt }}"/>
```

2024-04-18 16:55 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-hero_default_0_document_2_tablet-lg.png
If you change the apostrophes back to the original text do these regressions go away?

2024-04-19 15:06 UTC, olitharp-nci requested changes

2024-04-19 15:06 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-hero/nci-hero.stories.jsx
testing/ncids-css-testing/stories/components/nci-hero/nci-hero.default.stories.jsx

2024-04-19 15:06 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-hero/nci-hero.testcases.stories.jsx
testing/ncids-css-testing/stories/components/nci-hero/nci-hero.test-cases.stories.jsx

the other stories are using `test-cases` instead of `testcases`, let's just be consistent

2024-04-23 21:02 UTC, olitharp-nci requested changes
The previous requests have not been completed. There should be no regressions here. @andyvanavery31 I'm requesting your review again so you can make sure that the only regressions are expected changes. 

Rebase develop as well

2024-04-29 17:36 UTC, andyvanavery31 approved these changes
@karlikpj can you please revert the Right Single Quotation Mark (unicode U+2019) to the Apostrophe (unicode U+0027)? And then all of the regression images should not be changed (but please confirm)?

2024-04-30 14:05 UTC, andyvanavery31 commented
@karlikpj can you please add the following images to the regressions? (These should not cause any existing images to be changed, just adding new ones for completeness of our backstop testing)

- Hero Dark with Button Tablet Large
- Default Mobile Large
- Dark Without Button Tablet Large
- Test Cases With CTA Long Tablet Large
- Test Cases With CTA Spanish Tablet Large
- Variants With CTA Tablet Large
- Hero with Button Mobile Large

Cc: @olitharp-nci

2024-04-30 19:26 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-05-01 16:38 UTC, olitharp-nci requested changes

2024-05-01 16:38 UTC, olitharp-nci commented on packages/ncids-twig/components/nci-hero/nci-hero.twig
> +		<img src="{{ image.mobile }}" alt=""/>
Unresolving since this wasn't done

2024-05-01 19:30 UTC, olitharp-nci approved these changes

2024-05-01 19:53 UTC, merged