(#1667) Update Text Styles Utility Page
NCIOCPL/ncids pull request #1741
Opened 2024-06-10 12:19 UTC by karlikpj

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-06-13 14:53 UTC, bennettcc commented
Lindsay, Adriana, and Lilian approved on 6/13 - adding product checkmark

2024-06-13 14:54 UTC, bennettcc approved these changes

2024-06-13 17:26 UTC, olitharp-nci requested changes
first pass i'll have more later, please do not resolve the comments until i take a look

2024-06-13 17:26 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +      classes:
For estimated values you can use "italic" and "normal" here probably

2024-06-13 17:26 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +      classes:
estimated values, underline, line-through, none, none

2024-06-13 17:26 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +  - name: Text decoration color
`.text-underline` does not have sufficient contrast ratios

2024-06-13 17:26 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +  - name: Uppercase and lowercase
Not a note but `THE CELEBRATED JUMPING FROG OF CALAVERAS COUNTY` made me laugh because it looks like yelling about a frog 😂

2024-06-13 17:26 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +      classes:
Estimated values: uppercase, lowercase, none, none

i'm not gonna go through the rest, just add what the css value translates to to everything missing

2024-06-13 20:13 UTC, olitharp-nci reviewed
again don't resolve let me talk to bryan about the tabular

2024-06-13 20:13 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +        - class_name: 'text-tbottom'
`tbottom` is not a css value. fix these to the actual value

2024-06-13 20:13 UTC, olitharp-nci commented on docs/content/foundations/typography/text-styles.mdx
> +  - name: Tabular numerals
if both are not in we might want to remove this completely from our documentation. i'll talk to bryan

2024-06-14 14:23 UTC, bryanpizzillo commented on docs/content/foundations/typography/text-styles.mdx
> +          calculated_value: '-0.15em'
@karlikpj These calculated values are incorrect. Please be more careful - not reviewing work after copy/pasting slows down the reviews and acceptance of these PRs.

2024-06-14 14:27 UTC, bryanpizzillo commented on docs/src/components/layouts/utility-page-layout/utility-class-tables/text-style-demonstration.jsx
> +const StyleDemonstration = ({ utilityClassDisplayParams }) => {
can you please name this class to be text-underline-color-demonstration/TextUnderlineColorDemonstration. The reasoning being that this is not used for anything other that *that* use case.

2024-06-14 18:08 UTC, olitharp-nci requested changes

2024-06-14 18:08 UTC, olitharp-nci commented on docs/src/components/layouts/utility-page-layout/utility-class-tables/text-unerline-color-demonstration.jsx
this file should be called `unerline` instead of `underline`

2024-06-14 18:46 UTC, olitharp-nci requested changes
the workflow failed, but two more anyway, just some jsdoc

2024-06-14 18:46 UTC, olitharp-nci commented on docs/src/components/layouts/utility-page-layout/utility-class-tables/text-underline-color-demonstration.jsx
> + * @returns
oh update the jsdoc here, missing `@param utilityClassDisplayParams`

2024-06-14 18:46 UTC, olitharp-nci commented on docs/src/components/layouts/utility-page-layout/utility-class-tables/text-underline-color-demonstration.jsx
> + * @param {Array<TextUnderlineColorDemonstrationParams>} param0.utilityClassDisplayParams
this one too needs to be corrected 

`@param utilityClassDisplayParams`

2024-06-14 21:23 UTC, olitharp-nci approved these changes

2024-06-14 21:23 UTC, merged