(#1216) Flex Layout Utility Page
NCIOCPL/ncids pull request #1794
Opened 2024-07-17 13:09 UTC by karlikpj

Closes #1216

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-07-19 16:02 UTC, sarinapadilla approved these changes
Looks good to me! I'm seeing all of the utility modules from the [spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/doc2.aspx?sourcedoc=%7BAEAC153A-696A-4419-941B-142CC9B627F1%7D&file=USWDS_Utilities.xlsx&action=default&mobileredirect=true) and all of the examples are displaying correctly.

2024-07-29 14:38 UTC, olitharp-nci requested changes

2024-07-29 14:38 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/flex.mdx
> +                  <span className="site-utility-examples__class text-no-wrap">.flex-1</span>
please remove uswds-site classes.

2024-07-30 16:16 UTC, olitharp-nci requested changes
You should not be showing presentation code like this on the live site. What is shown to the user should only be code relevant for them to copy and paste.

This is bad:

![Screenshot 2024-07-30 at 10 57 31 AM](https://github.com/user-attachments/assets/031c4f42-e3a4-41dc-9c83-eb52577786de)

This is what is expected: 

![Screenshot 2024-07-30 at 10 59 35 AM](https://github.com/user-attachments/assets/c702ce80-84f7-41f9-8ccf-95e2595028c7)

Rework both this pr and #1803.

Also please create a ticket to go back and fix float as this detail was missed. Please have product review again.

2024-07-31 18:26 UTC, olitharp-nci requested changes

2024-07-31 18:26 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/flex.mdx
> +          <section>
remove the section wrappers

2024-08-01 14:06 UTC, olitharp-nci commented
Stop resolving conversations. Let the PR reviewer do it.

2024-08-01 17:37 UTC, olitharp-nci commented
Has content been reviewed? It doesn't seem that "The flex utility classes have not been modified from the U.S. Web Design System (USWDS). Refer to the USWDS Flex utility page for a complete listing of classes" is needed and it's repeated for each item.

2024-08-01 17:38 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/flex.mdx
> +          <section>
okie this looks good now

2024-08-01 18:11 UTC, olitharp-nci approved these changes

2024-08-01 19:33 UTC, andyvanavery31 approved these changes
Looks good to me!

2024-08-05 16:32 UTC, merged