(#1213) Display Utility Page
NCIOCPL/ncids pull request #1803
Opened 2024-07-23 19:30 UTC by karlikpj

Closes #1213

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-07-26 14:31 UTC, sarinapadilla commented
@karlikpj, when I scroll through the sticky positioning example, only the first heading is getting the styling. Headings 2, 3, and 4 are losing the styling.

2024-07-29 14:05 UTC, sarinapadilla approved these changes
Sticky headings are fixed. All of the utilities from the [spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BAEAC153A-696A-4419-941B-142CC9B627F1%7D&file=USWDS_Utilities.xlsx&action=default&mobileredirect=true) are included. This looks good to me!

2024-07-30 16:16 UTC, olitharp-nci requested changes
See https://github.com/NCIOCPL/ncids/pull/1794#pullrequestreview-2208135031

2024-07-31 18:32 UTC, olitharp-nci requested changes

2024-07-31 18:32 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/display.mdx
> +          <section>
A section element is only allowed if there is a heading. There is no heading, remove this. It doesn't appear a wrapper element is needed for this anyway.

2024-08-01 14:06 UTC, olitharp-nci commented
Stop resolving conversations. Let the PR reviewer do it.

2024-08-01 17:14 UTC, olitharp-nci approved these changes

2024-08-01 17:14 UTC, merged