(#1780) Adds sitewide search to docs site
NCIOCPL/ncids pull request #1810
Opened 2024-07-30 19:43 UTC by dlescarbeau

Closes #1780

2024-08-09 18:03 UTC, olitharp-nci requested changes
add the pr review template

2024-08-12 16:14 UTC, adrianacastaneda commented
@dlescarbeau Results pull browser titles instead of the page titles. Wondering if it could pull the page title instead since all the browser titles mentioning NCIDS can be a little repetitive and distracting for users.

Seeing that some meta descriptions are being pulled so that's great. I'll make sure to get those meta descriptions in for those that don't have them!

Thank you!

cc: @bennettcc

2024-08-12 16:19 UTC, bryanpizzillo commented
@adrianacastaneda browser titles are what the crawler finds. So, no we cannot pull in the page titles. What we probably should do is actually have `- NCI` at the end of the browser title, or add nothing at all. `- NCI` is actually the standard for browser titles and the search engine removes that from the titles it indexes.

2024-08-12 18:25 UTC, monika-jaeger commented
@dlescarbeau looks good so far! A few things:
- Can we change the H1 "Search Results," H3 "Results for: _____," and H4 "Results ## - ## of ##"  at the top and "Results ## - ## of ##" at the bottom to match our heading styles like on c.gov using Poppins? 
- Are we able to move the pagination component at the top on the same line as the H4 so there isn't extra white space before the results? 
- The "Show ## results per page" looks like it doesn't have space around the pager select, can we add a space before and after that to give some breathing room?

cc: @bennettcc

2024-08-12 18:31 UTC, olitharp-nci requested changes

2024-08-12 18:35 UTC, dlescarbeau commented
> * Can we change the H1 "Search Results," H3 "Results for: _____," and H4 "Results ## - ## of ##"  at the top and "Results ## - ## of ##" at the bottom to match our heading styles like on c.gov using Poppins?
> * Are we able to move the pagination component at the top on the same line as the H4 so there isn't extra white space before the results?
> * The "Show ## results per page" looks like it doesn't have space around the pager select, can we add a space before and after that to give some breathing room?

@monika-jaeger this entire page comes from the search app module, so layout things I'll have a hard time changing, but styles I should be able to change. This means specifically:

- Yes I should be able to update the headings with our fonts.
- I can't move the pagination component to the same line of the heading unfortunately, I fear the wizardry that would take with CSS. I will try but this one is unlikely.
- Yes, I can add some padding to that select box to add some space.

2024-08-12 19:29 UTC, bryanpizzillo commented on docs/src/scss/search-page.scss
> +@use "usa-pagination" as *;
@olitharp-nci I asked Derek to do this. This way we can use as much USWDS styling as possible for our non-ncids app. This should just be making the app's classes extend the `usa-pagination` classes so we save on css.

2024-08-13 15:23 UTC, andyvanavery31 commented
Noting the differences between digital platform site search and the introduction of this site search:
- The h1 size is different on the digital platform compared to this because the h1 on this PR uses the the h1 heading style from NCIDS and that is expected.
- The pagination style on the digital platform compared to this PR is different. The style on this PR is updated to match the current USWDS style from USWDS version 3.6.0.

Requested changes:
- Can you change the margin that is above the Results For: from 16.160px to 40px so it matches the style in the digital platform?

@dlescarbeau

2024-08-14 16:56 UTC, dlescarbeau commented on docs/src/scss/search-page.scss
> +@use "usa-pagination" as *;
@bryanpizzillo Should I put these back to the way it was? I'd changed it per Olivia's feedback.

2024-10-15 14:42 UTC, bryanpizzillo commented
This all predates Gatsby 5. PR #1829 completed this.

2024-10-15 14:42 UTC, closed without merging