(#1809) Float Util Code Examples
NCIOCPL/ncids pull request #1811
Opened 2024-07-30 21:24 UTC by karlikpj

Closes #1809

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-07-31 18:28 UTC, olitharp-nci requested changes

2024-07-31 18:28 UTC, olitharp-nci commented on pnpm-lock.yaml
you shouldn't have a pnpm-lock change. revert this, make sure you have both node 20 and pnpm 9 installed

2024-07-31 18:29 UTC, olitharp-nci requested changes

2024-07-31 18:29 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/float.mdx
> +          <section>
remove section element wrappers

2024-07-31 18:29 UTC, olitharp-nci commented on docs/content/foundations/layout-positioning/float.mdx
>            <section className="utility-examples">
shouldn't be here either

2024-08-01 14:04 UTC, olitharp-nci commented
Don't resolve conversations, let the PR reviewer do it.

2024-08-01 17:09 UTC, olitharp-nci approved these changes

2024-08-06 21:57 UTC, sarinapadilla commented
@karlikpj I noticed that the "Component Preview" headings around the Example Usage sections are missing when I compare the [PR page](https://designsystem-dev.cancer.gov/pr-1811/foundations/layout-positioning/float) to the [develop page](https://designsystem-dev.cancer.gov/develop/foundations/layout-positioning/float).

@adrianacastaneda @blilianyu @monika-jaeger what are your thoughts on this change?

2024-08-07 14:05 UTC, sarinapadilla approved these changes
Per @karlikpj, the removal of the "Component Preview" is expected.
> Its a different use of the component preview. The one on dev is Example Usage header - code preview then code snippet. But in the PR version it's Generated Preview - Example Usage Header - code snippet - we're omitting the code preview and using a generated example as the example uses extra css we don't want users to copy but needed for presentation. But that header is a part of the code preview/snippet module and can't be moved.

So this looks good to me!

2024-08-09 17:20 UTC, olitharp-nci commented
.

2024-08-09 17:21 UTC, olitharp-nci commented
.

2024-08-09 17:27 UTC, olitharp-nci commented
.

2024-08-09 18:04 UTC, merged