(#1691) adds usa section page to docs site
NCIOCPL/ncids pull request #1862
Opened 2024-09-27 16:10 UTC by dlescarbeau

Closes #1691

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-10-04 20:51 UTC, sarinapadilla requested changes
Please make these updates:
* The page title, browser title, and nav label should be "Section" rather than "USA Section"
* The "Variations" heading should be "Modifications"

2024-10-09 17:24 UTC, karlikpj approved these changes

2024-10-09 19:31 UTC, bryanpizzillo requested changes
Three main things hit me:
1. The `<section>` elements should not be `<section>` elements without a `aria-label` or `aria-labelledby`. This should be noted in the accessibility. If there is no label for the component, then a `<div>` element should be used instead.
2. Are we not showing off the look of the two variants.
3. We really should talk about the behavior when 2 same-themed sections are next to each other.

2024-10-10 13:42 UTC, andyvanavery31 commented
In addition to Bryan's points:
- We need a `<ul>` at the parent level of the unordered list in the [Modifications section](https://designsystem-dev.cancer.gov/pr-1862/components/section#modifications) in the table.
- The table heading under [Modifications](https://designsystem-dev.cancer.gov/pr-1862/components/section#modifications) should be "Modifier" not "Variant" to match the section and to match the rest of the component pages

2024-10-11 15:12 UTC, sarinapadilla approved these changes
Looks good to product!

2024-10-11 15:28 UTC, bryanpizzillo requested changes

2024-10-11 15:28 UTC, bryanpizzillo commented on docs/content/components/section.mdx
> +    - title: Applying Standard Page Margins
In testing with other developers, the `<section>` examples were missing. Please add 2 examples above the Applying Standard Page Margins example for:
* Making an Accessible Section using a Label
* Making an Accessible Section Labelled with Another Element

Feel free to use your discretion in adding good descriptions for each.

2024-10-11 15:28 UTC, bryanpizzillo commented on docs/content/components/section.mdx
> +        <section class="usa-section" aria-label="a section with a grid container">
Change this back to a div now that we will add other examples.

2024-10-11 17:05 UTC, olitharp-nci approved these changes

2024-10-14 14:00 UTC, bryanpizzillo approved these changes

2024-10-14 14:00 UTC, merged