(#1701) Cleanup Footer HTML
NCIOCPL/ncids pull request #1877
Opened 2024-10-17 18:54 UTC by karlikpj

Closes #1701

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2024-10-24 13:00 UTC, andyvanavery31 approved these changes
Passes Product review. For awareness, @adrianacastaneda the addition of the Storybook story with no form was added in this ticket, and we will address the Doc Site page with tickets #1335 and #1534

2024-10-25 15:14 UTC, olitharp-nci requested changes

2024-10-25 15:14 UTC, olitharp-nci commented on docs/content/components/footer.mdx
> +        `<a name="top"></a>`
This is bad guidance.

Not only do we not practice this anywhere on our production builds, specs allow anchors with #top to automatically point to the beginning of the document. 

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#sect23
* https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-the-fragment-identifier
* https://drafts.csswg.org/cssom-view/#scroll-to-the-beginning-of-the-document

2024-10-25 15:14 UTC, olitharp-nci commented on docs/content/components/footer.mdx
> +        `<a href='#top' aria-label=”Back To Top”>Back  To Top</a>`
```suggestion
        `<a href="#top" aria-label="Back To Top">Back  To Top</a>`
```

2024-10-29 14:26 UTC, andyvanavery31 approved these changes
Requested changes are approved and this passes product review.

2024-10-29 15:28 UTC, olitharp-nci approved these changes

2024-10-29 20:38 UTC, merged