(#1935) External Link Guide Cards
NCIOCPL/ncids pull request #1952
Opened 2024-12-17 22:58 UTC by karlikpj

Closes #1935

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2025-01-15 15:16 UTC, andyvanavery31 requested changes
Doc Site:
- Please rename the code snippet section, "Default Guide Card with External Links" to "Guide Card without Image and Description with External Links" for consistency
- The "Internal Link with Icon Override" button on both the Default and with Image and Description are missing the icon

Storybook:
- The Guide Card with Image and Description with External Links story should have correct spaces in the name (let me know if there is a character limit impacting this), it needs a description, and at large breakpoints, the title and the card are in different columns

Overall:
- At breakpoints close to the text wrapping, the icon crashes into the text (see 306px, 345px, and 417px on Storybook with Default with External Links when it is popped out into a separate window). Can we get that to not happen?

2025-01-15 21:05 UTC, andyvanavery31 commented
@karlikpj on storybook, I don't think we need the Guide Card with Image and Description and External Links to be a row, I think it should just be a single Guide Card with Image and Description. Could you please just make it look like [this story](https://designsystem-dev.cancer.gov/pr-1952/storybook/?path=/story/components-guide-card-variants-guide-card-with-image-and-description--single-guide-card-with-image-and-description-without-heading), but change the button anchors to match the External/External/Internal order that you have on the current story (and the default with external links)?

2025-01-16 14:04 UTC, andyvanavery31 commented
All Guide Card buttons are getting their text pushed slightly to the left even if there is no external link button. Can this be fixed? 

On Storybook, did the Default Guide Card with External Link story get deleted? I can't find it anymore. I think we should have the Default with External Link and the Guide Card with Image and Description and External Link stories in the Test Cases folder.

2025-01-16 19:55 UTC, andyvanavery31 commented
Please make the Storybook stories match the Scenarios in the ticket.

2025-01-23 16:50 UTC, olitharp-nci requested changes

2025-01-23 16:50 UTC, olitharp-nci commented on testing/ncids-css-testing/.backstop/reference/ncids_nci-guide-card_test-case_with-image_with-description_external-links_0_document_0_mobile.png
these images are having some issues, can you look into it?

2025-01-24 15:12 UTC, andyvanavery31 approved these changes

2025-01-24 19:25 UTC, olitharp-nci approved these changes

2025-01-24 20:41 UTC, olitharp-nci approved these changes

2025-01-24 20:41 UTC, merged