(#1932) External Links CTA Strip
NCIOCPL/ncids pull request #1956
Opened 2024-12-19 17:32 UTC by karlikpj

Closes #1932

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [ ] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [ ] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [ ] Unit tests have been updated or created to reflect any javascript changes.
- [ ] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

2025-01-08 17:35 UTC, olitharp-nci requested changes

2025-01-08 17:35 UTC, olitharp-nci commented on docs/content/components/hero.mdx
> +  - To override an INTERNAL link to be displayed as EXTERNAL, add the class `ncids-external-link` to the anchor (`<a>`) element.
`usa-link` uses `usa-link--external`, the footer pr used `external-link` this one is using `ncids-external-link`

2025-01-13 19:21 UTC, dlescarbeau commented on packages/ncids-css/packages/usa-button/internal/_external.scss
> +	// Display Block to wrap Icon with Text
I'm not sure if we should be adding external stuff to the button styles since they may not be consistent across components. (or maybe they are, something to double check..) Maybe try keeping the styles specific to CTA Strip and just targeting any `.usa-button` class within `.nci-cta-strip` ?

2025-01-14 16:14 UTC, dlescarbeau commented on docs/content/components/cta-strip.mdx
> +    - title: NCI CTA Strip with External Links
This is probably a good opportunity to port all of these docs site examples to use the twig template instead of copy/pasting the HTML here

2025-01-14 16:17 UTC, dlescarbeau commented on docs/content/components/hero.mdx
> +                  <a href="http://www.cancer.gov" class="usa-button ncids-external-link">
we should probably use something like `nci-cta-strip--external` rather than `usa-button--external` so that we can mark the component external as a whole, and then target the `usa-button` appropriately as a child of the external class instead

2025-01-14 16:54 UTC, karlikpj commented on docs/content/components/hero.mdx
> +                  <a href="http://www.cancer.gov" class="usa-button ncids-external-link">
my only concern here is that cta has three buttons, whereas promo block has one. CTA could only require one button needs external link icon - So placement of that modifier at the component level might be bad for CMS side.

However the external link mixin is inside of the CTA strip class so the selector is only targeting usa-button inside of cta-strip currently.
```ul.nci-cta-strip li .usa-button:not(.usa-button--external):not([href*=".gov"], [href*="mailto:"], [href*="javascript:"], [href*="public.govdelivery.com"], [href*="www.gov.uk"], [data-ncids-internal-link])..```

2025-01-14 17:20 UTC, dlescarbeau commented on docs/content/components/hero.mdx
> +                  <a href="http://www.cancer.gov" class="usa-button ncids-external-link">
disregard this comment as there are several links in the strip, don't know if that would work for this one.

2025-01-15 21:29 UTC, andyvanavery31 approved these changes

2025-01-22 21:41 UTC, olitharp-nci approved these changes

2025-01-22 21:46 UTC, dlescarbeau approved these changes

2025-01-22 23:48 UTC, merged