(#252) Implement visual testing
NCIOCPL/ncids pull request #269
Opened 2021-11-01 19:28 UTC by olitharp-nci

### Successful test:
https://github.com/NCIOCPL/ncids/actions/runs/1409322809

Artifact: [success-backstopjs.zip](https://github.com/NCIOCPL/ncids/files/7455664/success-backstopjs.zip)

### Failed test:
https://github.com/NCIOCPL/ncids/actions/runs/1409339745

Artifact: [failed-backstopjs.zip](https://github.com/NCIOCPL/ncids/files/7455666/failed-backstopjs.zip)

2021-11-08 16:59 UTC, bryanpizzillo requested changes
This is looking really good. I have some comments below, mostly around updating documentation.

2021-11-08 16:59 UTC, bryanpizzillo commented on README.md
> +| [`ncids-css-testing`](./packages/ncids-css-testing) | SASS/CSS testing package for NCIDS
Can you please move `ncids-css-testing` out of `packages` and into `testing`. If we have any automated stuff, we don't treat the testing package as a publishable thing,

2021-11-08 16:59 UTC, bryanpizzillo commented on packages/ncids-css-testing/README.md
> +
Can you please add some notes as to what the scripts in engine-scripts are for, what they do, and where to find docs

2021-11-08 16:59 UTC, bryanpizzillo commented on packages/ncids-css-testing/__tests__/ncids-css-testing.test.js
> +'use strict';
Can you remove this please if it is not a test.

2021-11-12 13:44 UTC, karlikpj approved these changes

2021-12-07 20:04 UTC, arcepaul approved these changes

2021-12-08 18:41 UTC, merged