(#257) Button component scss partials
NCIOCPL/ncids pull request #278
Opened 2021-11-19 19:06 UTC by olitharp-nci

Closes #257

2021-12-06 09:54 UTC, karlikpj approved these changes

2021-12-28 17:58 UTC, bryanpizzillo requested changes
Can you please rename your partials to follow our [naming scheme](https://github.com/NCIOCPL/ncids/wiki/The-Way#component-sass-partials)?

2021-12-28 19:09 UTC, bryanpizzillo approved these changes

2021-12-28 19:14 UTC, mworrest approved these changes
Looks great to me.

2021-12-28 19:36 UTC, merged