(#262) Build site alert component
NCIOCPL/ncids pull request #319
Opened 2022-01-31 17:46 UTC by olitharp-nci

Closes #262

https://designsystem-dev.cancer.gov/pr-xxx/components/xxx

2022-02-01 14:18 UTC, bryanpizzillo requested changes
Some initial notes.

2022-02-01 14:18 UTC, bryanpizzillo commented on docs/content/design-tokens/state-tokens.mdx
> +| <ColorChip color={"#bb0e3d"} /> | `'emergency'`       | `'cranberry-60'` | `$theme-color-emergency`       | `#bb0e3d` |
Does emergency-dark change as well? I would assume these two are related.

2022-02-01 14:18 UTC, bryanpizzillo commented on packages/ncids-css/scss/base/settings/_settings-color.scss
>  $theme-color-emergency-dark: 'red-warm-80' !default;
See my above comment about emergency dark.

2022-02-01 14:18 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/usa-site-alert/_all.scss
> +@import "internal/nci-emergency";
This should just be
```
@import "./nci-emergency"
@import "./nci-info"
```

2022-02-10 15:32 UTC, bryanpizzillo requested changes
Can you please add a link on the documentation site homepage to the site alert?

2022-02-24 23:06 UTC, mworrest commented
I am seeing purple for the link color on the blue alert. It should be blue. Is there going to be the open/close functionality or is that in another ticket?

![Screen Shot 2022-02-24 at 6 05 02 PM](https://user-images.githubusercontent.com/4921685/155622568-a8cdf269-676c-4e2b-ad8e-dd3a62552739.png)

2022-02-25 02:11 UTC, olitharp-nci commented
> I am seeing purple for the link color on the blue alert. It should be blue. Is there going to be the open/close functionality or is that in another ticket?
> 
> ![Screen Shot 2022-02-24 at 6 05 02 PM](https://user-images.githubusercontent.com/4921685/155622568-a8cdf269-676c-4e2b-ad8e-dd3a62552739.png)

A purple link usually means it's a visited href. I'll take a look.

2022-02-25 14:44 UTC, olitharp-nci commented
@mworrest, it should be blue now as expected, let me know if you still see purple 

![Screen Shot 2022-02-25 at 8 42 58 AM](https://user-images.githubusercontent.com/85901679/155734695-856987eb-f7dd-4fee-bae9-2b7a9ca2ecc8.png)

2022-02-25 17:15 UTC, meglake commented
Michelle creating design ticket (will be a spike) to look into changing the link color across the site to avoid contrast issue noted in the PR and determine what happens if we make the dark be the default for link color. Putting in design backlog, potentially for sprint 25.

2022-02-25 17:20 UTC, mworrest commented
Created spike ticket: https://github.com/NCIOCPL/ncids/issues/348

2022-02-25 21:55 UTC, bryanpizzillo requested changes
TO FIX:
* Add the component to scss/components/all
* Fix gatsby-browser to import all, and update docs on how to use uswds.
* Also there are nits having to do with how we document the TS types and not using `@typedef` but doing the comments over the elements

FOR FUTURE:
2 issues that we can track as separate items:
1. BUG - The NCICloseButton for the SiteAlert uses the same Cookie name.
2. REQ ISSUE - The Expand/Collapse should also use a cookie

2022-02-25 22:18 UTC, olitharp-nci commented
https://github.com/NCIOCPL/ncids/issues/349
https://github.com/NCIOCPL/ncids/issues/350

2022-02-25 23:11 UTC, arcepaul commented on docs/content/components/site-alert.mdx
> +- `aria-label` must be unique and descriptive to what the alert is so that screen readers
unfinished thought

2022-02-25 23:15 UTC, arcepaul commented on docs/content/components/site-alert.mdx
> +
I don't see the cross for the dismissible

2022-02-28 13:29 UTC, bryanpizzillo approved these changes
This all looks good to me.

2022-02-28 13:33 UTC, arcepaul approved these changes

2022-02-28 16:30 UTC, mworrest approved these changes

2022-02-28 17:43 UTC, merged