(#296) CSS for Extended Header
NCIOCPL/ncids pull request #322
Opened 2022-02-03 18:28 UTC by karlikpj

- Default Desktop and Primary + Mega
- Adding Mobile DOM

2022-02-08 17:45 UTC, bryanpizzillo requested changes
Some initial overall comments: 
1.  The code should be in `ncids-css/scss/components/usa-header` as we are creating a variant on top of the usa-header, not our own block.
2. The partial currently named `_header.scss` should be named `_nci-extended.scss` as it is the nci-extended variant.
3. Please place the "guts" of the header into the `ncids-css/scss/components/usa-header/internal` directory.
    * This would apply to `./navigation`, `./navigation-mobile` and the contents of the file.
 4. Any BEM elements should be named accordingly. (e.g. `.nci-search` should probably be something like `.usa-footer__nci-search`) The same goes for `.nci-mobile-container`
 5. There should be only 1 partial that references uswds components. That is `ncids-css/scss/components/usa-header/_nci-extended.scss`
 6. Settings should not be placed in `ncids-css/scss/components/usa-header`, but in `ncids-css/scss/base/settings` in the same named file as USWDS. This partial should be added to `ncids-css/scss/base/global/_required.scss`.  
      * Although this looks like it comes from `stylesheets/theme` in USWDS which we do not seem to have a parallel for.

2022-02-24 20:40 UTC, bryanpizzillo requested changes
A few things at first glance:
1. Can you please make the menu items in the primary nav be anchor links -- e.g. for www.cancer.gov this will be `<a href="/about-cancer">` etc? 
    * Your JS for the megamenu should turn them into buttons.
2. Can you please put the NCI logo in place of the placeholder? 
3. Drop the example before your example
4. Move the Guidance to the top, move the variants below the guidance.
5. Fix the heading "When to use the list" 
6. Do something with the Accessibility section, right now it is just an elipses

2022-02-25 17:36 UTC, bryanpizzillo commented
@karlikpj Can you please make a prototype site and demo off the www.cancer.gov & www.cancer.gov/espanol menus to @mworrest ?

Also please update the design system documentation site header to be the header.

2022-02-25 20:18 UTC, mworrest commented
The down arrows of the menu should not be blue. Does this help illustrate the states? 
![menu-states-children](https://user-images.githubusercontent.com/4921685/155794724-0d4c91b6-36a9-4d2c-adad-90a9cc81ca91.jpg)
![menu-states-no-children](https://user-images.githubusercontent.com/4921685/155794726-f9a378f0-c431-44b0-aa36-e34bb088206a.jpg)

2022-03-03 14:12 UTC, mworrest approved these changes
The styles (default and hover of main nav items) look good to me.

2022-03-08 16:34 UTC, olitharp-nci commented on docs/content/components/header.mdx
> +<Code className="html">{NciExtended}</Code>
Instead of 

```
<Code className="html">
```

Can you add

```markdown
    ```html
    // initial component html 
    ```
```

2022-03-08 16:38 UTC, olitharp-nci commented on yarn.lock
> +anymatch@^3.0.3:
I don't think I'm seeing any changes to `package.json`, might wanna revert this file

2022-03-08 17:58 UTC, bryanpizzillo requested changes
I am seeing an _nci-header.scss in the nci-header component folder. What is this exactly? I would assume this should not exist since it is the nci-extended.

2022-03-08 17:58 UTC, bryanpizzillo commented on docs/src/components/header.jsx
> +//import { Link } from 'gatsby';
Remove the comment if it is not needed.

2022-03-08 17:58 UTC, bryanpizzillo commented on docs/src/scss/_components.scss
> +@import '@nciocpl/ncids-css/scss/components/nci-header/nci-extended';
This should be referencing an `all` partial.

2022-03-08 17:58 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/nci-header/internal/_navigation.scss
> +@mixin add-before(
Please do not place mixins in the component styling. I know USWDS does that but this can cause issues down the road.

2022-03-08 17:58 UTC, bryanpizzillo commented on packages/ncids-js/src/components/usa-header/nci-header.component.ts
> +export interface NCIHeaderOptions {
one export per file please. So put this in nci-header-options.ts.

2022-03-08 17:58 UTC, bryanpizzillo commented on packages/ncids-js/src/components/usa-header/nci-header.component.ts
> +	headerOptions?: string;
can you make this be whatever it should or should not be?

2022-03-08 17:58 UTC, bryanpizzillo commented on packages/ncids-js/src/components/usa-header/nci-header.component.ts
> +export class NCIHeader {
So what is your plan for supporting all the different types of headers? Will they be derrived classes?

2022-04-06 14:58 UTC, bryanpizzillo commented
Closing as this has been pulled in as a new PR, #378

2022-04-06 14:58 UTC, closed without merging