Closes #298 Mobile Menu Functionality
NCIOCPL/ncids pull request #456
Opened 2022-05-12 19:12 UTC by karlikpj

Closes #298

2022-05-17 22:18 UTC, bryanpizzillo commented
@karlikpj can you fix the commit message here to be:
(#298) Mobile Menu Functionality

Thanks

2022-06-30 19:36 UTC, bryanpizzillo commented on packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts
> +			const results = await this.adaptor.getInitialMenuId(path);
This I think should be:
`const results = await this.adaptor.getNavigationLevel(this.adaptor.getInitialMenuId())`

2022-06-30 20:03 UTC, olitharp-nci commented
Closes #298

2022-07-11 15:13 UTC, olitharp-nci commented
![Screen Shot 2022-07-11 at 10 12 28 AM](https://user-images.githubusercontent.com/85901679/178297276-2e7eab82-4a5e-4176-8186-10b1f54c6215.png)

The mobile menu button color should not change
https://publicis.invisionapp.com/console/Header-&-Footer-Wireframes-cl17806xjx3ho01x42xix33gc/cl178079m77pi01uqi3oen68y/play

2022-07-11 17:06 UTC, olitharp-nci requested changes

2022-07-11 17:06 UTC, olitharp-nci commented on testing/ncids-js-testing/src/MockMobileMenuAdaptor.ts
> +			console.log(err);
console.error(err);

2022-07-11 17:06 UTC, olitharp-nci commented on packages/ncids-js/src/components/nci-header/utils/mobile-menu/mobile-menu.ts
> +			path = '/';
Looks like there is missing code coverage for the first part of the if statement. Second half looks covered?

2022-07-11 18:25 UTC, olitharp-nci requested changes

2022-07-11 18:25 UTC, olitharp-nci commented on packages/ncids-js/src/components/nci-header/__tests__/mobile-menu/mobile-menu-adaptor.mock.ts
> +		console.log(id);
remove

2022-07-12 17:12 UTC, arcepaul commented on testing/ncids-js-testing/public/index.html
> -			<div class="nci-header-mobilenav__overlay"></div>
need to update everywhere

2022-07-16 17:33 UTC, bryanpizzillo requested changes
The text of the Search button does not submit the search form. The Search button text should be switched from a `<label>` element to a `<span>`.
```
 <button class="usa-button nci-header-search__search-button" type="submit" aria-label="Search">
          <span class="nci-header-search__label" aria-hidden="true">Search</span>
```

2022-07-19 15:01 UTC, olitharp-nci approved these changes

2022-07-19 15:26 UTC, bennettcc commented
This PR has been passed to @mworrest and @meglake for review

2022-07-20 18:09 UTC, mworrest approved these changes
I can only interact with it so much on the example site, but the various states captured in storybook seem to cover the use cases.

2022-07-28 13:41 UTC, merged