(#374) Back To Top
NCIOCPL/ncids pull request #527
Opened 2022-08-02 20:23 UTC by karlikpj

Closes(#374)

2022-08-08 19:01 UTC, blilianyu commented
Based on the comps, it should be “BACK TO TOP” and not “Return to top” and on mobile the text is swapped out with an arrow.
 
https://publicis.invisionapp.com/console/Back-to-top-cl178a6l13rzm01w5kmj9hrxn/cl178a70u3rzo01w570gchjan/play

2022-08-08 21:30 UTC, olitharp-nci requested changes

2022-08-08 21:30 UTC, olitharp-nci commented on packages/ncids-css/scss/components/nci-back-to-top/_back-to-top.scss
> +	transition: all .25s ease-in-out;
can you format this file?

2022-08-08 21:30 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/utils/footer-back-to-top.component.ts
> +		console.log('int');
clean up console logs

2022-08-08 21:30 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/utils/footer-back-to-top.component.ts
> +	public static create(element: HTMLElement): NCIBackToTop {
Shouldn't be a component (more like footer collapse than NCI subscribe that the footer uses)

2022-08-08 21:30 UTC, olitharp-nci commented on docs/content/index.mdx
> +- [Back To Top](./components/backtotop)
remove

2022-08-09 13:21 UTC, arcepaul commented on docs/content/components/footer.mdx
> +		<a href="#"><span>BACK TO TOP</span></a>
use #top here

2022-08-09 13:39 UTC, arcepaul commented on docs/src/components/footer/nci-big.jsx
> +					<span>BACK TO TOP</span>
Can we use a text-transform here?  Screen readers don't like all caps and might do strange things

2022-08-09 16:02 UTC, arcepaul commented on docs/content/components/footer.mdx
> +		<a href="#top"><span>Back To Top</span></a>
aria-label missing here

2022-08-11 16:34 UTC, blilianyu commented
@karlikpj Can we make that whole area clickable? Or we can't because of USWDS?

2022-08-15 19:47 UTC, blilianyu approved these changes

2022-08-16 20:49 UTC, olitharp-nci requested changes

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-css/scss/components/nci-back-to-top/_back-to-top.scss
> +	text-transform: uppercase;
can you reformat this file?

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-css/scss/components/nci-back-to-top/_back-to-top.scss
> +.nci-footer__return-to-top {
we don't have a nci-footer, so probably should be:

```suggestion
.usa-footer__nci-return-to-top {
```

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-css/scss/components/usa-footer/_nci-big.scss
> +@import '../nci-back-to-top/back-to-top';
add new line to end of file

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/__tests__/nci-footer-back-to-top.test.ts
> +//import userEvent from '@testing-library/user-event';
remove commented out code

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/nci-big-footer.component.ts
> +import { NCIBackToTop } from './utils/footer-back-to-top.component';
file should just be 

```suggestion
import { NCIBackToTop } from './utils/footer-back-to-top';
```

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/utils/footer-back-to-top.component.ts
> +		this.element.classList.remove('show', 'hide', 'nci-footer__return-to-top');
see note in scss file about naming

```suggestion
		this.element.classList.remove('show', 'hide', 'usa-footer__nci-return-to-top');
```

2022-08-16 20:49 UTC, olitharp-nci commented on packages/ncids-js/src/components/usa-footer/utils/footer-back-to-top.component.ts
> +		this.element.classList.add('nci-footer__return-to-top', 'hide');
here too

2022-08-16 20:49 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-footer/usa-footer.stories.jsx
> +export * from './nci-big.back-to-top-es.stories';
new line at end of file

2022-08-17 14:36 UTC, olitharp-nci approved these changes

2022-08-18 14:22 UTC, merged