(#579) External Link Icon in Buttons
NCIOCPL/ncids pull request #591
Opened 2022-09-22 15:49 UTC by karlikpj

Closes (#579)

2022-10-17 17:39 UTC, olitharp-nci commented
Remove parenthesis in description so github links to ticket `Closes #579`

2022-10-17 17:47 UTC, blilianyu commented
@karlikpj  Can we increase margin-left from 1px to 10px? The icon is too tight
<img width="188" alt="Screen Shot 2022-10-17 at 1 46 04 PM" src="https://user-images.githubusercontent.com/51677926/196246976-9ca1b9e9-3e3d-4053-af7b-5ce5e4881f93.png">

2022-10-17 17:54 UTC, olitharp-nci requested changes
We need guidance for this variant so the documentation site can be updated

2022-10-17 17:54 UTC, olitharp-nci commented on packages/ncids-css/scss/components/usa-button/_all.scss
> +@import 'internal/external';
add new line at end of file

2022-10-17 17:54 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/usa-button/usa-button.stories.jsx
> +export * from "./external-link.stories";
new line at end of file

2022-10-17 17:55 UTC, karlikpj commented
@blilianyu can you please update comment to use one of the size tokens from https://designsystem.digital.gov/design-tokens/spacing-units/
(1 or 1.5 i feel would be best)

2022-10-18 15:09 UTC, monika-jaeger approved these changes
Looks good after the increased space!

2022-10-18 16:18 UTC, sarinapadilla approved these changes
This passes product review!

2022-10-19 17:55 UTC, olitharp-nci approved these changes

2023-01-30 19:10 UTC, dlescarbeau approved these changes

2023-01-30 19:33 UTC, bryanpizzillo requested changes
Please add code and documentation so that:
1. We can force showing the external link if it matches a ".gov" address. (E.g. it matches https://www.govgrantfinder.com)
2. We can force NOT showing the external link if the link is a URL we do not consider to be external such as someproject.ideascale.com.

2023-02-01 16:44 UTC, olitharp-nci approved these changes

2023-02-01 16:56 UTC, arcepaul approved these changes

2023-02-01 21:57 UTC, merged