(#611) Printer Style Alert
NCIOCPL/ncids pull request #623
Opened 2022-10-14 19:43 UTC by karlikpj

Closes(#611)

2022-10-17 17:38 UTC, olitharp-nci requested changes

2022-10-17 18:06 UTC, karlikpj commented on packages/ncids-css/scss/components/usa-site-alert/internal/_print.scss
>  		display: none;
Yes, and I will do the same when updating 612

2022-10-17 18:14 UTC, olitharp-nci approved these changes

2022-10-17 20:36 UTC, monika-jaeger approved these changes

2022-10-18 14:53 UTC, arcepaul approved these changes

2022-10-18 14:53 UTC, merged