(#595) Adds Example Pages & Scenarios
NCIOCPL/ncids pull request #624
Opened 2022-10-17 18:22 UTC by dlescarbeau

- Closes #595

- Main Example Page is now a list of links to other pages
- Moves Inner Content Page to a linked page
- Adds CGov Homepage
- Adds Microsite Homepage
- Adds Landing Page
- Adds placeholder sections for future page components

2022-10-25 18:24 UTC, bryanpizzillo requested changes
A couple of things:
1. Can you please move the README.md into the ncids-js-testing root?
2. Can you organize the folders a bit under public? e.g.,
     * `index.html`
     * `/inner-pages`
         * `inner-page.html`
     * `/home-landing`
        * `cgov-home.html`
        * ...
3. I would like to see the `footer`, `header`, banner, site alert components to be shared and not copy/paste if possible.

2022-10-25 19:51 UTC, bryanpizzillo commented
> A couple of things:
> 
> 1. Can you please move the README.md into the ncids-js-testing root?
> 2. Can you organize the folders a bit under public? e.g.,
>    
>    * `index.html`
>    * `/inner-pages`
>      
>      * `inner-page.html`
>    * `/home-landing`
>      
>      * `cgov-home.html`
>      * ...
> 3. I would like to see the `footer`, `header`, banner, site alert components to be shared and not copy/paste if possible.

2. Ok, so organizing the folders is impossible right now cause images are relative right now.
3. imports are only available with the html-loader which is going to be another LOE, so let's backlog that.

2022-10-28 13:19 UTC, olitharp-nci commented
lgtm - other than bryan's note about resetting `package-lock.json`

2022-11-01 16:33 UTC, arcepaul approved these changes

2022-11-01 16:37 UTC, bryanpizzillo approved these changes

2022-11-01 17:41 UTC, olitharp-nci approved these changes

2022-11-01 21:37 UTC, blilianyu approved these changes

2022-11-01 21:38 UTC, merged