(#548) Hero Cta Strip
NCIOCPL/ncids pull request #650
Opened 2022-11-08 16:14 UTC by karlikpj

Closes #548

2022-11-28 15:27 UTC, bryanpizzillo requested changes
I have a couple of things below.

Also, can you please add back in the gray boxes under the CTA strip on the inner page of the example site? No one should be approving the look and feel with it crashing on to the footer.

Finally, we really need to see this with the widescreen breakpoint working. Once we get "new dev" done for the MVP, we can make a release branch and start working on 2.0.

2022-11-28 15:27 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/_all.scss
> +@import 'uswds/dist/scss/components/step-indicator';
Why have these been added? I had removed all components we had not worked on yet.

2022-11-28 15:27 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/nci-cta-strip/internal/_cta-buttons.scss
> +.nci-cta-button {
This should be an element, e.g. `.nci-cta-strip__button` if it is not just going to be a `usa-button` for the element.

2022-11-28 15:27 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/nci-cta-strip/internal/_cta-strip.scss
> +
Is this meant to be empty?

2022-11-28 15:27 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/nci-cta-strip/internal/_cta-strip.scss
> +
same emptyness...

2022-11-28 15:27 UTC, bryanpizzillo commented on packages/ncids-css/scss/components/nci-cta-strip/internal/_cta-buttons.scss
> +.nci-cta-button {
also if you are using the "primary" style as indicated with the theme token, you should be importing that style definition.

2023-02-08 15:05 UTC, arcepaul commented
For people that are non-sighted or using screen readers, there is no indication that the link is external.

2023-02-08 15:29 UTC, blilianyu approved these changes

2023-02-08 15:57 UTC, arcepaul approved these changes

2023-02-08 16:08 UTC, merged