(#598) Promoblock With/Without Image
NCIOCPL/ncids pull request #683
Opened 2022-12-05 17:58 UTC by dlescarbeau

Closes #598

- Adds Promoblock and alternating Promoblocks to CGov Home example page

2023-01-12 16:58 UTC, bryanpizzillo commented on packages/ncids-css/scss/settings/_settings-utilities.scss
> +	'tablet-lg': true,
This should be reverted an moved to the index.scss for the example site. Adding tablet-lg blows up the utilities. We don't care about the CSS size for example site or storybook, so we should only turn on utilities/expand the size of utilities in those things that specifically need them.

2023-01-12 19:03 UTC, bryanpizzillo requested changes
Based on the 1/12/2022 design meeting the left and right padding on the promo blocks should be the same between mobile and tablet-lg. The padding of the default (i.e. the one without an image) is the correct padding. 

There was another issue discovered that the heading weight was 700. It should be 600, and that would come from settings. (e.g. `$theme-font-weight-bold: 600 !default;`) This is probably not isolated to the promoblocks unless it is some mixin usage we had not done before.

------

To bad PR request changes do not have a nice resolve button. Anyway this was is fixed in the current version.

2023-01-12 19:58 UTC, bryanpizzillo commented on packages/ncids-css/scss/settings/_settings-utilities.scss
> +	'tablet-lg': true,
This has been changed.

2023-01-20 20:45 UTC, sarinapadilla approved these changes
Product approved!!

2023-01-24 23:43 UTC, bryanpizzillo approved these changes

2023-01-24 23:45 UTC, merged