(#777) Updates Title Colors for Card Link States
NCIOCPL/ncids pull request #788
Opened 2023-02-27 16:33 UTC by dlescarbeau

- Closes #777

2023-02-27 18:50 UTC, karlikpj approved these changes

2023-02-28 14:52 UTC, bryanpizzillo requested changes
Can you please check if we have hover/active and visited backstop scenarios for these.

2023-02-28 16:51 UTC, bennettcc commented
@dlescarbeau Feedback from Alex on 2/28 - We should add the hover state behavior on breakpoints below 1023px, for users viewing on a small desktop or resizing the browser window to below 1024. (Mobile and tablet user will of course, not see the hover state of links)

2023-03-01 20:30 UTC, olitharp-nci requested changes

2023-03-01 20:30 UTC, olitharp-nci commented on packages/ncids-css/scss/components/nci-card/internal/_nci-card.scss
> +			&:focus img {
swap hover and focus order
LoVe For HAte

2023-03-01 20:30 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/components/nci-card/default.stories.jsx
> +      <a href="javascript:void(0);" aria-label="Feature Card">
do you try `href="#"`? certain versions of react will throw an error with `href="javascript:void(0);"`. If # works we could avoid the headache later. If not, we can worry about it then

2023-03-02 16:04 UTC, andyvanavery approved these changes
Reviewed and approved by Product and the Client (gave verbal approval on 02MAR2023). This successfully implements the correct link colors on Feature Cards.

2023-03-02 17:34 UTC, arcepaul approved these changes

2023-03-06 15:37 UTC, bryanpizzillo approved these changes

2023-03-06 15:38 UTC, merged