(#824) Enable twig for css testing
NCIOCPL/ncids pull request #829
Opened 2023-03-27 15:16 UTC by olitharp-nci

Closes #824 
Closes #825 
Closes #827 
Closes #835

2023-03-31 19:30 UTC, bryanpizzillo requested changes
See below

2023-03-31 19:30 UTC, bryanpizzillo commented on package.json
> +		"test:twig": "lerna run twigcs"
Change `test:twig` to be
`"test:twig": "docker pull ghcr.io/nciocpl/twigcs-docker:v1.0.1  && lerna run twigcs"`

2023-04-03 15:39 UTC, andyvanavery approved these changes
This PR correctly enables twig and passes through the Button Group from USWDS to NCIDS per review by Product and Design. This passes review.

2023-04-04 13:55 UTC, bryanpizzillo requested changes
I think there is just one thing left...

2023-04-04 13:55 UTC, bryanpizzillo commented on testing/ncids-css-testing/stories/uswds-native/.editorconfig
> +[*.{json,js}]
This should be json and twig, not js. We own the js and it should follow our standards.

2023-04-04 15:16 UTC, bryanpizzillo approved these changes

2023-04-04 15:16 UTC, merged