(#874) Uswds Table Component
NCIOCPL/ncids pull request #906
Opened 2023-04-12 16:15 UTC by karlikpj

Closes #874

2023-04-17 12:29 UTC, karlikpj commented
[Storybook](https://designsystem-dev.cancer.gov/pr-906/storybook/?path=/story/components-nci-autocomplete--default)

2023-04-17 13:31 UTC, olitharp-nci requested changes

2023-04-17 13:31 UTC, olitharp-nci commented on yarn.lock
> -array-flatten@^3.0.0:
did you `yarn install` or `lerna bootstrap` without the frozen lockfile flag? Shouldn't need any changes to yarn.lock

2023-04-17 13:31 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-table/src/index.js
> +const select = require("../../uswds-core/src/js/utils/select");
You shouldn't need this file

2023-04-17 13:31 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-table/src/usa-table.scenarios.js
> +		label: 'usa-table sortable',
need focus/hover/active checks for `.usa-table__header__button` for all three variants

2023-04-17 13:31 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-table/src/usa-table.stories.js
> +export const Default = () => <TestCase css={css} html={Template.bind({})(DefaultContent)} />;
Match USWDS

```text
- Table
  - Default
  - Borderless
  - Striped
  - Sortable
  - Scrollable
    - Default
    - Striped
    - Compact
    - Compact Striped
  - Stacked
    - Default
    - Borderless
    - With Header
    - With Header Borderless
```

2023-04-17 13:31 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-table/src/usa-table.stories.js
> +export const Default = () => <TestCase css={css} html={Template.bind({})(DefaultContent)} />;
Scrollable missing

2023-04-17 13:31 UTC, olitharp-nci commented on packages/ncids-css/package.json
> -		"usa-add-aspect": "helper mixin, not a component"
don't delete `usa-add-aspect` comment

2023-04-18 00:11 UTC, arcepaul approved these changes

2023-04-18 15:36 UTC, olitharp-nci approved these changes
Approved - decided we will use the chop off due to the `overflow-y:hidden` as a visual representation that scrollable is working for now. We will add a backlog item to add scrollbars per story later

2023-04-18 15:44 UTC, merged