(#872) Step Indicator Component
NCIOCPL/ncids pull request #907
Opened 2023-04-12 20:15 UTC by karlikpj

Closes #872

2023-04-13 21:27 UTC, olitharp-nci requested changes

2023-04-13 21:27 UTC, olitharp-nci commented on packages/ncids-css/package.json
> +		"//": "usa-content, usa-dark-background, usa-display, usa-intro, usa-link, usa-paragraph, usa-step-indicator, usa-prose all required for uswds-typography.",
change this back too - step indicator shouldn't be required for uswds-typography to work

2023-04-13 21:27 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-step-indicator/src/index.scss
> +@forward "uswds-helpers";
add end of line to end of file so github happy

2023-04-13 21:54 UTC, olitharp-nci requested changes

2023-04-13 21:54 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-step-indicator/src/index.scss
> +@forward "uswds-helpers";
oh my bad. uswds-global also imports uswds-helpers. sorry, should have caught that at my last look over

2023-04-14 14:31 UTC, olitharp-nci approved these changes

2023-04-17 15:27 UTC, dlescarbeau approved these changes

2023-04-17 19:01 UTC, monika-jaeger approved these changes
Approved for product.

2023-04-17 19:51 UTC, merged