(#873) Summary Box Component
NCIOCPL/ncids pull request #909
Opened 2023-04-13 16:38 UTC by karlikpj

Closes #873

2023-04-13 21:07 UTC, olitharp-nci requested changes

2023-04-13 21:07 UTC, olitharp-nci commented on packages/ncids-css/package.json
> +		"//": "usa-content, usa-dark-background, usa-display, usa-intro, usa-link, usa-paragraph, usa-summary-box, usa-prose all required for uswds-typography.",
i don't see that import in typography? what is this for?

2023-04-13 21:07 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-summary-box/src/index.scss
> +@forward "uswds-fonts";
i don't think you need the font import here

2023-04-13 21:07 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-summary-box/src/usa-summary-box.scenarios.js
> +		viewports: [
this one has links - can we get focus/active/hover selector scenarios?

2023-04-20 14:37 UTC, arcepaul approved these changes

2023-04-21 13:53 UTC, merged