(#875) Tool tip Pass though
NCIOCPL/ncids pull request #927
Opened 2023-04-19 16:04 UTC by karlikpj

Closes #875

2023-04-19 20:02 UTC, olitharp-nci requested changes

2023-04-19 20:02 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-tooltip/src/index.scss
> +@forward "uswds-utilities";
need to import buttons for storybook test event thought it's not a dependency of tooltip

2023-04-26 19:50 UTC, olitharp-nci approved these changes

2023-04-27 21:44 UTC, bennettcc approved these changes

2023-04-27 21:45 UTC, bennettcc commented
Approved by product on 4/27

2023-05-01 14:37 UTC, arcepaul approved these changes

2023-05-01 14:37 UTC, merged