(#852) Text Input Pass though
NCIOCPL/ncids pull request #932
Opened 2023-04-20 06:59 UTC by karlikpj

Closes #931

2023-04-20 21:31 UTC, olitharp-nci requested changes

2023-04-21 16:14 UTC, olitharp-nci requested changes
textarea looks off - probably need to import usa-textarea in the story

also plz add focus selector to the interactive elements, "text input focus" is a fake focus state

2023-04-21 20:27 UTC, monika-jaeger approved these changes
Approved for product.

2023-04-25 13:25 UTC, bennettcc commented
@olitharp-nci This PR is ready for your re-review please

2023-04-26 14:33 UTC, dlescarbeau approved these changes

2023-04-26 15:43 UTC, olitharp-nci approved these changes

2023-04-27 19:25 UTC, arcepaul approved these changes

2023-04-27 19:25 UTC, merged