(#856) Adds usa-select input passthrough
NCIOCPL/ncids pull request #950
Opened 2023-04-20 19:00 UTC by dlescarbeau

- Closes #856

2023-04-20 21:26 UTC, olitharp-nci requested changes

2023-04-20 21:26 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-select/src/usa-select.scenarios.js
> +		storyId: 'uswds-components-select--default',
can you add focus/click selectors to ui elements

2023-04-20 21:26 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-select/src/usa-select.scenarios.js
> +		storyId: 'uswds-components-select--default',
multiple test variant needs regressions as well - though i'm not sure how we would test multiple selections yet, we might need to chat about this later with the group

2023-04-20 21:26 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-select/src/usa-select.stories.js
> +export const Default = () => <TestCase css={css} html={Template.bind({})()} />;
Missing MultipleTest

2023-04-20 21:29 UTC, olitharp-nci requested changes

2023-04-20 21:29 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-select/src/index.scss
> +@forward "usa-select";
needs imports for usa-form and usa-label

uswds doesn't have separate css for each test so they are inheriting all the styles, if you check the test against https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/?path=/story/components-form-inputs-select--select you'll see some missing styles

2023-04-25 16:59 UTC, olitharp-nci approved these changes

2023-04-26 11:47 UTC, karlikpj approved these changes

2023-04-27 19:46 UTC, andyvanavery approved these changes
Passes Product review.

2023-04-28 20:19 UTC, arcepaul approved these changes

2023-04-28 20:19 UTC, merged