(#849) File Input Pass Through
NCIOCPL/ncids pull request #951
Opened 2023-04-24 13:43 UTC by karlikpj

Closes #849

2023-04-26 14:31 UTC, bennettcc commented
Approved by product on 4/26

2023-04-26 16:17 UTC, karlikpj commented
This is currently having A11Y contrast issues. This is due to the font size/background color combination that is produced by our customized tokens. Our selected colors for links do not pass for small text contrast unless on white. Attached is an options which can pass by setting the fonts to 16px / the background white and using the blue for the border.
![screenshot_2023-04-26_at_10 00 44_am_720](https://user-images.githubusercontent.com/66697447/234638560-cca0316e-4ff3-4504-91a3-0342d353acf1.png)

2023-06-22 13:50 UTC, karlikpj commented
on hold for color correction

2023-07-21 16:56 UTC, olitharp-nci requested changes
Need a scenario for upload state

Currently looks like:
<img width="1345" alt="Screenshot 2023-07-21 at 11 54 00 AM" src="https://github.com/NCIOCPL/ncids/assets/85901679/1f9230d3-432b-4dff-811f-9745e280d06b">

Need to hear from design about your suggestion https://github.com/NCIOCPL/ncids/pull/951#issuecomment-1523696425

2023-07-24 18:14 UTC, monika-jaeger commented
@olitharp-nci @karlikpj I would be ok with the suggestion in [the above comment](https://github.com/NCIOCPL/ncids/pull/951#issuecomment-1523696425). Let me know if you need more details to implement. Thanks!

2023-07-28 12:15 UTC, karlikpj commented
![Screenshot 2023-07-27 at 10 03 02 AM](https://github.com/NCIOCPL/ncids/assets/66697447/8850445f-d073-45ee-a0a0-52d88e8ba263)
![Screenshot 2023-07-27 at 10 14 49 AM](https://github.com/NCIOCPL/ncids/assets/66697447/9f5ff5c4-eeb0-43f1-a3ef-ada5c7375ceb)
working on backstop tests to capture this specific UI state.

2023-08-02 21:05 UTC, olitharp-nci requested changes

2023-08-02 21:05 UTC, olitharp-nci commented on testing/ncids-css-testing/stories/uswds-native/usa-file-input/src/img/logo.jpg
remove file

2023-08-02 21:06 UTC, olitharp-nci approved these changes

2023-08-11 13:18 UTC, sarinapadilla approved these changes

2023-08-11 15:18 UTC, dlescarbeau approved these changes

2023-08-15 21:02 UTC, arcepaul approved these changes

2023-08-15 21:02 UTC, merged